### ISSUE TITLE
CLI runTest broken

### ISSUE THREAD

**Issue by pwdng** [Strider-CD/strider#1001]
When trying to run a test from the CLI, strider reports the following error:

/usr/lib/node_modules/strider/lib/routes/api/session.js:27
      req.session.passport.user = user.id;
                                ^

TypeError: Cannot set property 'user' of undefined
    at /usr/lib/node_modules/strider/lib/routes/api/session.js:27:33
    at /usr/lib/node_modules/strider/lib/models/user.js:147:14
    at /usr/lib/node_modules/strider/node_modules/bcryptjs/dist/bcrypt.js:261:17
    at /usr/lib/node_modules/strider/node_modules/bcryptjs/dist/bcrypt.js:1198:21
    at Immediate.next (/usr/lib/node_modules/strider/node_modules/bcryptjs/dist/bcrypt.js:1078:21)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

**Comment by pwdng** [comment]
The issue seems to be linked to the version of passport.
In commit c6a20f9b8d54e1d2bcf4403bec746c6e8183d3a2, dependency was updated to 0.3.2.
Using version 0.2.2 solved the problem and everything else seems to work ok.

See http://stackoverflow.com/questions/32187787/passport-js-github-strategy-callback-always-returns-typeerror-cannot-set-prope

Was there any reason for the update expect for using the latest version?

**Comment by oliversalzburg** [comment]
First of all, yes, that change was only made so that the latest version is used, not to address an actual issue.  
That being said, I would much rather get to the source of this than to downgrade again.

Please explain to me which tests you're running and how. If you're running from the CLI, I don't even know how passport plays a role in this.

**Comment by pwdng** [comment]
All I'm doing is starting a build job from shell:

`strider runTest -l abc@xyz.com -p password -j foo/bar -b master`

This in turn calls the script `strider-cli/run.js`
All this script does is use the HTTP API to authenticate and start a test.
It seems logical that passport should therefore be used.

I understand that you'd want to use the latest version of passport but currently, that breaks the runTest command.
Personally, I'm not familiar enough with passport to fix the existing code so that it is compatible with the latest version. If you or someone else can do it, that would be great. Otherwise, I'll stick to my fix for the time being. 

Thanks

**Comment by knownasilya** [comment]
@oliversalzburg in the never version of passport, for some reason `req.session.passport` isn't always set, so the above error occurs. I read somewhere that the user shouldn't even be set on that, but on req, but this seems to be tied to some of the socket stuff since it uses the session. I've yet to unwind exactly what needs to be done..

**Comment by oliversalzburg** [comment]
@knownasilya We generally use `request.user` as well in our codebase.

**Comment by knownasilya** [comment]
Yeah, but I think the session gets passed on the socket, so that would be missing the user if we set it on `req.user`, but maybe we just add that to the socket. Got to find the uses of that socket thing.

**Comment by knownasilya** [comment]
Fixed in master
