### ISSUE TITLE
Can not login with user created via "strider addUser"

### ISSUE THREAD

**Issue by MattiusAscentMS** [Strider-CD/strider#1012]
Connect
500 CastError: Cast to ObjectId failed for value "586e756ce73a40e1703858ce" at path "_id" for model "user"
   at MongooseError.CastError (/home/strider/strider/node_modules/mongoose/lib/error/cast.js:26:11)
   at ObjectId.cast (/home/strider/strider/node_modules/mongoose/lib/schema/objectid.js:147:13)
   at ObjectId.castForQuery (/home/strider/strider/node_modules/mongoose/lib/schema/objectid.js:187:15)
   at cast (/home/strider/strider/node_modules/mongoose/lib/cast.js:229:32)
   at Query.cast (/home/strider/strider/node_modules/mongoose/lib/query.js:2752:12)
   at Query.findOne (/home/strider/strider/node_modules/mongoose/lib/query.js:1353:10)
   at Function.findOne (/home/strider/strider/node_modules/mongoose/lib/model.js:1343:13)
   at Function.findById (/home/strider/strider/node_modules/mongoose/lib/model.js:1271:15)
   at /home/strider/strider/lib/auth.js:112:10
   at pass (/home/strider/strider/node_modules/passport/lib/authenticator.js:347:9)
   at Authenticator.deserializeUser (/home/strider/strider/node_modules/passport/lib/authenticator.js:352:5)
   at SessionStrategy.authenticate (/home/strider/strider/node_modules/passport/lib/strategies/session.js:53:28)
   at attempt (/home/strider/strider/node_modules/passport/lib/middleware/authenticate.js:348:16)
   at authenticate (/home/strider/strider/node_modules/passport/lib/middleware/authenticate.js:349:7)
   at Layer.handle [as handle_request] (/home/strider/strider/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/home/strider/strider/node_modules/express/lib/router/index.js:312:13)
   at /home/strider/strider/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/home/strider/strider/node_modules/express/lib/router/index.js:330:12)
   at next (/home/strider/strider/node_modules/express/lib/router/index.js:271:10)
   at initialize (/home/strider/strider/node_modules/passport/lib/middleware/initialize.js:53:5)
   at Layer.handle [as handle_request] (/home/strider/strider/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/home/strider/strider/node_modules/express/lib/router/index.js:312:13)
   at /home/strider/strider/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/home/strider/strider/node_modules/express/lib/router/index.js:330:12)
   at next (/home/strider/strider/node_modules/express/lib/router/index.js:271:10)
   at /home/strider/strider/lib/app.js:124:5
   at Layer.handle [as handle_request] (/home/strider/strider/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/home/strider/strider/node_modules/express/lib/router/index.js:312:13)

**Comment by knownasilya** [comment]
Which version of node are you using?

**Comment by MattiusAscentMS** [comment]
v4.2.6

**Comment by MattiusAscentMS** [comment]
strider@1.9.4 /home/strider/strider
└── mongoose@4.7.6

**Comment by MattiusAscentMS** [comment]
Upgrading to Node v4.7.2 has fixed the issue!

**Comment by knownasilya** [comment]
Excellent, seems like an issue with mongoose.

**Comment by Churanos** [comment]
i have the same issue.

strider@1.9.5 C:\Users\Churanos\Projects\striderCD
`-- mongoose@4.8.6
