### ISSUE TITLE
unsupported content encoding "utf-8"

### ISSUE THREAD

**Issue by Colin6618** [Strider-CD/strider#1021]
```
2017-02-16T07:38:43.486Z - error: UnsupportedMediaTypeError: unsupported content encoding "utf-8"
    at contentstream (/home/striderCD/node_modules/body-parser/lib/read.js:170:13)
    at read (/home/striderCD/node_modules/body-parser/lib/read.js:54:14)
    at jsonParser (/home/striderCD/node_modules/body-parser/lib/types/json.js:127:5)
    at Layer.handle [as handle_request] (/home/striderCD/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/striderCD/node_modules/express/lib/router/index.js:312:13)
    at /home/striderCD/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/striderCD/node_modules/express/lib/router/index.js:330:12)
    at next (/home/striderCD/node_modules/express/lib/router/index.js:271:10)
    at urlencodedParser (/home/striderCD/node_modules/body-parser/lib/types/urlencoded.js:100:7)
    at Layer.handle [as handle_request] (/home/striderCD/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/striderCD/node_modules/express/lib/router/index.js:312:13)
    at /home/striderCD/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/striderCD/node_modules/express/lib/router/index.js:330:12)
    at next (/home/striderCD/node_modules/express/lib/router/index.js:271:10)
    at bodySetter (/home/striderCD/lib/middleware.js:45:3)
    at Layer.handle [as handle_request] (/home/striderCD/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/striderCD/node_modules/express/lib/router/index.js:312:13)
    at /home/striderCD/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/striderCD/node_modules/express/lib/router/index.js:330:12)
    at next (/home/striderCD/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/home/striderCD/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/home/striderCD/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/striderCD/node_modules/express/lib/router/index.js:312:13)
    at /home/striderCD/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/striderCD/node_modules/express/lib/router/index.js:330:12)
    at next (/home/striderCD/node_modules/express/lib/router/index.js:271:10)
    at query (/home/striderCD/node_modules/express/lib/middleware/query.js:44:5)
    at Layer.handle [as handle_request] (/home/striderCD/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/striderCD/node_modules/express/lib/router/index.js:312:13)
    at /home/striderCD/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/striderCD/node_modules/express/lib/router/index.js:330:12)
    at next (/home/striderCD/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/home/striderCD/node_modules/express/lib/router/index.js:176:3)
    at EventEmitter.handle (/home/striderCD/node_modules/express/lib/application.js:173:10)
    at Server.app (/home/striderCD/node_modules/express/lib/express.js:38:9)
    at Server.<anonymous> (/home/striderCD/node_modules/engine.io/lib/server.js:435:22)
    at Server.<anonymous> (/home/striderCD/node_modules/socket.io/lib/index.js:275:16)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)

```

**Comment by knownasilya** [comment]
What's the context here? What's the payload and how was it received? Looks like from the browser via socket? Which browser?

**Comment by Colin6618** [comment]
I would reopen  until  the problem occured again.

**Comment by Colin6618** [comment]
it occured again, debug info as below. (sensitive info has been replaced by *)

```
 strider-runner-core:job Job "58e459850a81c2393b8989f3" status: command.start { '0': 'command.start',
  '1':
   { command: 'bash -e -x -c \'echo "SUCCESS: daily 流程"\necho "//***/path"\'',
     started: 2017-04-05T02:45:31.867Z,
     plugin: 'custom',
     time: 2017-04-05T02:45:31.867Z } } +27ms
  strider-runner-core:job Job "58e459850a81c2393b8989f3" status: stderr { '0': 'stderr',
  '1': '+ alias \'rm=rm -i\'\n+ alias \'mv=mv -i\'\n+ \'[\' -f /etc/bashrc \']\'\n+ . /etc/bashrc\n++ \'[\' \'\' \']\'\n++ shopt -q login_shell\n++ \'[\' 0 -gt 199 \']\'\n++ umask 022\n++ SHELL=/bin/bash\n++ for i in \'/etc/profile.d/*.sh\'\n++ \'[\' -r /etc/profile.d/256term.sh \']\'\n++ \'[\' \'\' \']\'\n++ . /etc/profile.d/256term.sh\n+++ local256=\n+++ \'[\' -n \'\' \']\'\n+++ \'[\' -n \'\' \']\'\n+++ unset local256\n++ for i in \'/etc/profile.d/*.sh\'\n++ \'[\' -r /etc/profile.d/colorgrep.sh \']\'\n++ \'[\' \'\' \']\'\n++ . /etc/profile.d/colorgrep.sh\n+++ /usr/libexec/grepconf.sh -c\n' } +6ms
  strider-runner-core:job Job "58e459850a81c2393b8989f3" status: stderr { '0': 'stderr',
  '1': '+++ alias \'grep=grep --color=auto\'\n+++ alias \'egrep=egrep --color=auto\'\n+++ alias \'fgrep=fgrep --color=auto\'\n++ for i in \'/etc/profile.d/*.sh\'\n++ \'[\' -r /etc/profile.d/colorls.sh \']\'\n++ \'[\' \'\' \']\'\n++ . /etc/profile.d/colorls.sh\n+++ \'[\' \'!\' -t 0 \']\'\n+++ return\n++ for i in \'/etc/profile.d/*.sh\'\n++ \'[\' -r /etc/profile.d/lang.sh \']\'\n++ \'[\' \'\' \']\'\n++ . /etc/profile.d/lang.sh\n+++ sourced=0\n+++ \'[\' -n zh_CN.UTF-8 \']\'\n+++ saved_lang=zh_CN.UTF-8\n+++ \'[\' -f /root/.i18n \']\'\n+++ LANG=zh_CN.UTF-8\n+++ unset saved_lang\n+++ \'[\' 0 = 1 \']\'\n+++ unset sourced\n+++ unset langfile\n++ for i in \'/etc/profile.d/*.sh\'\n++ \'[\' -r /etc/profile.d/less.sh \']\'\n++ \'[\' \'\' \']\'\n++ . /etc/profile.d/less.sh\n+++ \'[\' -x /usr/bin/lesspipe.sh \']\'\n+++ export \'LESSOPEN=||/usr/bin/lesspipe.sh %s\'\n+++ LESSOPEN=\'||/usr/bin/lesspipe.sh %s\'\n++ for i in \'/etc/profile.d/*.sh\'\n++ \'[\' -r /etc/profile.d/vim.sh \']\'\n++ \'[\' \'\' \']\'\n++ . /etc/profile.d/vim.sh\n+++ \'[\' -n \'4.2.46(1)-release\' -o -n \'\' -o -n \'\' \']\'\n+++ \'[\' -x /usr/bin/id \']\'\n++++ /usr/bin/id -u\n' } +4ms
  strider-runner-core:job Job "58e459850a81c2393b8989f3" status: stderr { '0': 'stderr',
  '1': '+++ ID=0\n+++ \'[\' -n 0 -a 0 -le 200 \']\'\n+++ return\n++ for i in \'/etc/profile.d/*.sh\'\n++ \'[\' -r /etc/profile.d/which2.sh \']\'\n++ \'[\' \'\' \']\'\n++ . /etc/profile.d/which2.sh\n+++ alias \'which=alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde\'\n++ unset i\n++ unset -f pathmunge\n+ echo \'SUCCESS: daily 流程\'\n+ echo //***/path\n' } +3ms
  strider-runner-core:job Job "58e459850a81c2393b8989f3" status: stdout { '0': 'stdout',
  '1': 'SUCCESS: daily 流程\n//***/path\n' } +2ms
  strider-runner-core:job Job "58e459850a81c2393b8989f3" status: command.done { '0': 'command.done',
  '1': { exitCode: 0, time: 2017-04-05T02:45:31.911Z, elapsed: 44 } } +4ms
  strider-runner-core:job Job "58e459850a81c2393b8989f3" status: plugin-data { '0': 'plugin-data',
  '1':
   { plugin: 'custom',
     data: { cleanupCmd: 'passed' },
     method: 'extend',
     path: undefined } } +3ms
  strider-runner-core:job Job "58e459850a81c2393b8989f3" status: phase.done { '0': 'phase.done',
  '1':
   { phase: 'cleanup',
     time: 2017-04-05T02:45:31.915Z,
     exitCode: 0,
     next: undefined,
     elapsed: 52 } } +1ms
  strider-simple-runner [runner:simple-runner] Job done without error. Project: fe/** Job ID: 58e459850a81c2393b8989f3 +4ms
2017-04-05T02:53:57.572Z - error: UnsupportedMediaTypeError: unsupported content encoding "utf-8"
    at contentstream (/home/striderCD/node_modules/body-parser/lib/read.js:170:13)
    at read (/home/striderCD/node_modules/body-parser/lib/read.js:54:14)
    at jsonParser (/home/striderCD/node_modules/body-parser/lib/types/json.js:127:5)
    at Layer.handle [as handle_request] (/home/striderCD/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/striderCD/node_modules/express/lib/router/index.js:312:13)
    at /home/striderCD/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/striderCD/node_modules/express/lib/router/index.js:330:12)
    at next (/home/striderCD/node_modules/express/lib/router/index.js:271:10)
    at urlencodedParser (/home/striderCD/node_modules/body-parser/lib/types/urlencoded.js:100:7)
    at Layer.handle [as handle_request] (/home/striderCD/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/striderCD/node_modules/express/lib/router/index.js:312:13)
    at /home/striderCD/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/striderCD/node_modules/express/lib/router/index.js:330:12)
    at next (/home/striderCD/node_modules/express/lib/router/index.js:271:10)
    at bodySetter (/home/striderCD/lib/middleware.js:45:3)
    at Layer.handle [as handle_request] (/home/striderCD/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/striderCD/node_modules/express/lib/router/index.js:312:13)
    at /home/striderCD/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/striderCD/node_modules/express/lib/router/index.js:330:12)
    at next (/home/striderCD/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/home/striderCD/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/home/striderCD/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/striderCD/node_modules/express/lib/router/index.js:312:13)
    at /home/striderCD/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/striderCD/node_modules/express/lib/router/index.js:330:12)
    at next (/home/striderCD/node_modules/express/lib/router/index.js:271:10)
    at query (/home/striderCD/node_modules/express/lib/middleware/query.js:44:5)
    at Layer.handle [as handle_request] (/home/striderCD/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/striderCD/node_modules/express/lib/router/index.js:312:13)
    at /home/striderCD/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/striderCD/node_modules/express/lib/router/index.js:330:12)
    at next (/home/striderCD/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/home/striderCD/node_modules/express/lib/router/index.js:176:3)
    at EventEmitter.handle (/home/striderCD/node_modules/express/lib/application.js:173:10)
    at Server.app (/home/striderCD/node_modules/express/lib/express.js:38:9)
    at Server.<anonymous> (/home/striderCD/node_modules/engine.io/lib/server.js:435:22)
    at Server.<anonymous> (/home/striderCD/node_modules/socket.io/lib/index.js:275:16)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
  strider:backchannel job.prepare - error opening/processing project's `strider.json` file:  Error: not implemented
    at Object.getFile (/home/striderCD/node_modules/strider-git/webapp.js:40:10)
    at striderJson (/home/striderCD/lib/backchannel.js:38:21)
    at /home/striderCD/lib/backchannel.js:79:7
    at Function.<anonymous> (/home/striderCD/node_modules/mongoose/lib/model.js:3420:16)
    at /home/striderCD/node_modules/mongoose/lib/model.js:1861:14
    at /home/striderCD/node_modules/async/internal/parallel.js:35:9
    at /home/striderCD/node_modules/async/internal/once.js:12:16
    at iteratorCallback (/home/striderCD/node_modules/async/eachOf.js:52:13)
    at /home/striderCD/node_modules/async/internal/onlyOnce.js:12:16
    at /home/striderCD/node_modules/async/internal/parallel.js:32:13
    at apply (/home/striderCD/node_modules/lodash/_apply.js:15:25)
    at /home/striderCD/node_modules/lodash/_overRest.js:32:12
    at model.callbackWrapper (/home/striderCD/node_modules/mongoose/lib/model.js:1831:11)
    at next_ (/home/striderCD/node_modules/hooks-fixed/hooks.js:89:34)
    at fnWrapper (/home/striderCD/node_modules/hooks-fixed/hooks.js:186:8)
    at /home/striderCD/node_modules/mongoose/lib/model.js:3420:16
    at /home/striderCD/node_modules/mongoose/lib/model.js:269:5
    at /home/striderCD/node_modules/mongoose/lib/model.js:155:7
    at /home/striderCD/node_modules/mongoose/node_modules/mongodb/lib/collection.js:525:5
    at /home/striderCD/node_modules/mongoose/node_modules/mongodb/lib/collection.js:703:5
    at handleCallback (/home/striderCD/node_modules/mongoose/node_modules/mongodb/lib/utils.js:95:56)
    at /home/striderCD/node_modules/mongoose/node_modules/mongodb/lib/bulk/unordered.js:465:9
    at handleCallback (/home/striderCD/node_modules/mongoose/node_modules/mongodb/lib/utils.js:95:56)
    at resultHandler (/home/striderCD/node_modules/mongoose/node_modules/mongodb/lib/bulk/unordered.js:413:5)
    at /home/striderCD/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9) +8m
  strider-simple-runner [runner:simple-runner] Queued new job. Project: fe/** Job ID: 58e45c490a81c2393b898a22 +32ms
  strider:backchannel new job was created +1ms
  strider:backchannel job saved +60ms
  strider-simple-runner [runner:simple-runner] Job started. Project: fe/** Job ID: 58e45c490a81c2393b898a22 +1s
  strider-simple-runner Initializing plugins... +0ms
  strider-simple-runner Initializing plugin 'webhooks'... +1ms
  strider-simple-runner Initializing plugin 'custom'... +0ms
  strider-simple-runner Initializing plugin 'ssh_deploy'... +0ms
  strider-runner-core:job Creating new job "58e45c490a81c2393b898a22" for project "fe/**" using provider "git". +6ms
  strider-runner-core:job Running job "58e45c490a81c2393b898a22"... +1ms
  strider-runner-core:job Job "58e45c490a81c2393b898a22" runs: custom { cmd:
   { command: 'bash',
     args:
      [ '-e',
        '-x',
        '-c',
        'git --version\nnode --version\nnpm --version\ncnpm --version' ] },
  env:
   { PATH: ':::/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin',
     HOME: '/root',
     LANG: 'zh_CN.UTF-8',
     SSH_AUTH_SOCK: undefined,
     PAAS_NAME: 'strider' } } +2ms

```

**Comment by Colin6618** [comment]
"version": "1.9.4" node 6.9.4

**Comment by knownasilya** [comment]
How is the job started?

**Comment by Colin6618** [comment]
start the job via api

**Comment by Colin6618** [comment]
it's my router code 


<details>
```


async function start2(type, branch, repo, user) {

  let data = querystring.stringify({
    "type": type,
    "branch": branch,
    "message": user + ' ' + type
  });

  let headers = {'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': data.length};
  let options = {
    auth: '**',
    method: 'POST',
    hostname: "**",
    port: **,
    path: `/${repo}/start`,
    headers: headers
  };

  return new Promise((resolve, reject) => {
    let req = http.request(options, (res) => {
      const statusCode = res.statusCode;
      const contentType = res.headers['content-type'];
      let cookies = res.headers['set-cookie'] || []
      let chunks = []
      res.on('data', (chunk) => chunks.push(chunk))

      res.on('end', () => {

        let buf = Buffer.concat(chunks)
        let result = {
          body: buf.toString(),
          cookies: cookies,
          statusCode: statusCode
        }
        logger.info(result)
        if (statusCode == 200) {
          resolve(result)
        }
        else {
          // consume response data to free up memory
          res.resume();
          reject(new Error(result.body));

        }

      })

      res.on('error', reject)
    })

    req.on('error', reject)

    req.write(data)

    req.end()
  })
}

```

</details>

**Comment by knownasilya** [comment]
ContentType should be application/json
