### ISSUE TITLE
Cant start Strider

### ISSUE THREAD

**Issue by milewski** [Strider-CD/strider#1022]
```
2017-02-17T01:33:19.711Z - info: Using MongoDB URL: mongodb://database:27017
2017-02-17T01:33:19.768Z - warn: No SMTP creds - forgot password flow will not work
2017-02-17T01:33:20.168Z - info: RUNNER INIT

/opt/strider/src/node_modules/strider-bitbucket/lib/webapp.js:65
        return done(new Error(`Failed to parse json body: ${e.message}; ${body
                              ^
2017-02-17T01:33:20.176Z - info: failed to load plugin bitbucket Unexpected token ILLEGAL SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /opt/strider/src/node_modules/strider-extension-loader/lib/index.js:324:29
    at /opt/strider/src/node_modules/strider-extension-loader/lib/index.js:355:11
    at /opt/strider/src/node_modules/strider-extension-loader/node_modules/async/lib/async.js:511:21
    at /opt/strider/src/node_modules/strider-extension-loader/node_modules/async/lib/async.js:227:13
    at /opt/strider/src/node_modules/strider-extension-loader/node_modules/async/lib/async.js:111:13
    at Array.forEach (native)
    at _each (/opt/strider/src/node_modules/strider-extension-loader/node_modules/async/lib/async.js:32:24)
    at async.each (/opt/strider/src/node_modules/strider-extension-loader/node_modules/async/lib/async.js:110:9)
    at _asyncMap (/opt/strider/src/node_modules/strider-extension-loader/node_modules/async/lib/async.js:226:9)
    at Object.map (/opt/strider/src/node_modules/strider-extension-loader/node_modules/async/lib/async.js:204:23)
2017-02-17T01:33:20.178Z - error: [SyntaxError: Unexpected token ILLEGAL; error loading plugin bitbucket]
2017-02-17T01:33:20.178Z - error: Failed to load plugins
2017-02-17T01:33:20.179Z - info: Marking zombie jobs as finished...
2017-02-17T01:33:20.456Z - info: loaded templates
2017-02-17T01:33:20.605Z - info: initalized static directories
2017-02-17T01:33:20.609Z - info: 0 zombie jobs marked as finished
2017-02-17T01:33:20.610Z - error: Strider seems to have been misconfigured - there are no available runner plugins. Please make sure all dependencies are up to date.
31592 died 1 null
31604 forked

##############################################################
#
#   !!! MONGOOSE WARNING !!!
#
#   This is an UNSTABLE release of Mongoose.
#   Unstable releases are available for preview/testing only.
#   DO NOT run this in production.
#
##############################################################

2017-02-17T01:33:22.517Z - info: Using MongoDB URL: mongodb://database:27017
2017-02-17T01:33:22.572Z - warn: No SMTP creds - forgot password flow will not work
2017-02-17T01:33:22.962Z - info: RUNNER INIT
```

**Comment by oliversalzburg** [comment]
What Node version?

**Comment by Colin6618** [comment]
Delete the SMTP configuration in your config file and try again @Milewski

**Comment by Milewski** [comment]
Oh sorry. i missed the github notification on this...

Actually i am using strider with docker.. and the node version being installed is old.. i tried to update it to the latests version along with the latest npm.. but still got the same error above.

i have tried going manually to the source folder and run these commands

```
git checkout . && git pull
rm -rf node_modules
npm install // (using the latest npm/node here already)
npm run build && npm run start
```

**Comment by israelroldan** [comment]
@milewski @oliversalzburg this is definitely an issue with Strider-CD/docker-strider rather than this repository. I've submitted Strider-CD/docker-strider#17 to fix this.

**Comment by milewski** [comment]
God I wish Github had a better notification system... I totally missed this.. 

And yeah that was totally something to do with the strider docker version.. I solved that by creating my own container.. Good to know that a fix is comming.. Then I don't need to worry about my container anymore.
