### ISSUE TITLE
Unhandled rejection RangeError: attempt to write outside buffer bounds

### ISSUE THREAD

**Issue by xgalen** [Strider-CD/strider#1031]
Hi,

After updating `Strider` today to the latest version (`1.9.6`), using node v7.5.0 and npm v4.1.2 I get this error while testing a project.

The tests work on my computer and on the integration environment if I run them manually.

I think it could be related with length of the response, because other projects are working without problems.

```
2017-05-30T16:41:52.227Z - warn: Unhandled rejection RangeError: attempt to write outside buffer bounds
    at Buffer.write (buffer.js:556:11)
    at serializeBoolean (/home/ubuntu/strider/node_modules/bson/lib/bson/parser/serializer.js:143:48)
    at serializeInto (/home/ubuntu/strider/node_modules/bson/lib/bson/parser/serializer.js:763:17)
    at serializeObject (/home/ubuntu/strider/node_modules/bson/lib/bson/parser/serializer.js:308:18)
    at serializeInto (/home/ubuntu/strider/node_modules/bson/lib/bson/parser/serializer.js:618:17)
    at serializeObject (/home/ubuntu/strider/node_modules/bson/lib/bson/parser/serializer.js:308:18)
    at serializeInto (/home/ubuntu/strider/node_modules/bson/lib/bson/parser/serializer.js:776:17)
    at serialize (/home/ubuntu/strider/node_modules/bson/lib/bson/bson.js:58:27)
    at Query.toBin (/home/ubuntu/strider/node_modules/mongodb-core/lib/connection/commands.js:140:25)
    at Pool.write (/home/ubuntu/strider/node_modules/mongodb-core/lib/connection/pool.js:973:23)
    at executeWrite (/home/ubuntu/strider/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:73:10)
    at WireProtocol.update (/home/ubuntu/strider/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:88:3)
    at Server.update (/home/ubuntu/strider/node_modules/mongodb-core/lib/topologies/server.js:582:35)
    at Server.update (/home/ubuntu/strider/node_modules/mongodb/lib/server.js:392:17)
    at updateDocuments (/home/ubuntu/strider/node_modules/mongodb/lib/collection.js:1055:19)
    at Collection.update (/home/ubuntu/strider/node_modules/mongodb/lib/collection.js:1094:44)
    at NativeCollection.(anonymous function) [as update] (/home/ubuntu/strider/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:126:28)
    at model.Model.$__handleSave (/home/ubuntu/strider/node_modules/mongoose/lib/model.js:188:23)
    at model.Model.$__save (/home/ubuntu/strider/node_modules/mongoose/lib/model.js:214:9)
    at model.Model.save (/home/ubuntu/strider/node_modules/mongoose/lib/model.js:321:15)
    at model._done (/home/ubuntu/strider/node_modules/hooks-fixed/hooks.js:101:24)
    at _next (/home/ubuntu/strider/node_modules/hooks-fixed/hooks.js:64:28)
    at fnWrapper (/home/ubuntu/strider/node_modules/hooks-fixed/hooks.js:186:8)
    at model.<anonymous> (/home/ubuntu/strider/node_modules/mongoose/lib/plugins/sharding.js:16:5)
    at _next (/home/ubuntu/strider/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/home/ubuntu/strider/node_modules/hooks-fixed/hooks.js:186:8)
    at /home/ubuntu/strider/node_modules/mongoose/lib/plugins/saveSubdocs.js:34:7
    at /home/ubuntu/strider/node_modules/mongoose/node_modules/async/internal/once.js:12:16
```

**Comment by xgalen** [comment]
Well, maybe it's not related with Strider. Let me do more checks.
