### ISSUE TITLE
 Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by rmsystemadmin** [Strider-CD/strider#1041]
I'm receiving this error when attempting to do a build from Github. Any ideas?

```
TypeError: Cannot read property 'split' of undefined
    at /Users/administrator/Projects/strider/node_modules/strider-git/worker.js:70:30
    at ChildProcess.<anonymous> (/Users/administrator/Projects/strider/node_modules/strider-git/worker.js:59:22)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

I'm using **Slack** and **Custom Scripts** as far as plugins go, and the default runner.

Thanks!

**Comment by knownasilya** [comment]
Does `git --version` work on your machine?

**Comment by rmsystemadmin** [comment]
Yep

**Comment by rmsystemadmin** [comment]
THAT WAS IT. Renaming XCode was what caused the issue, because it broke Git. Thanks for your help. Closing.

**Comment by knownasilya** [comment]
I'm going to keep this issue open because they code has actual issues
