### ISSUE TITLE
Error: Cannot find module '../build/Release/bson'

### ISSUE THREAD

**Issue by inkylamb** [Strider-CD/strider#1066]
`.715Z - error: (node:13240) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/gxc/Desktop/continue-integration/strider-continue/node_modules/strider-webhooks/node_modules/bson/ext/index.js:15:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/gxc/Desktop/continue-integration/strider-continue/node_modules/strider-webhooks/node_modules/bson/lib/bson/index.js:3:24)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/gxc/Desktop/continue-integration/strider-continue/node_modules/strider-webhooks/webapp.js:1:78)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18) code: 'MODULE_NOT_FOUND' }
2018-09-07T03:23:40.048Z - error: js-bson: Failed to load c++ bson extension, using pure JS version
2018-09-07T03:23:40.336Z - info: Express server listening on port 3000 in development mode
2018-09-07T03:23:40.341Z - error: (node:13240) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany,or bulkWrite instead.
^C`
### environment
* centos 7
* mongodb 3.6.3
* node  v10.6.0
* npm 6.4.1 
* "mongoose": "^5.2.8"
### description 
i had find this problem in google and baidu they say this problem is made by mongoose and i can't find this file in ..node_modules\mongodb\node_modules\bson\ext\index.js to sovle this problem . so i think maybe there are something wrong in other problem . i chang this file node_modules/strider-webhooks/node_modules/bson/lib/bson/index.js:3:24) and find the promble err was disappear but also has a little trouble in running .so i hope can sovle this problem . thank you very much .

**Comment by knownasilya** [comment]
That is an error that is handled, see the text in the log after the error:

> error: js-bson: Failed to load c++ bson extension, using pure JS version

What is the issue you are experiencing and what version of Strider are you using?

**Comment by inkylamb** [comment]
The version of Strider is "strider-cli": "^2.0.0" .  I find the problem is here <img id="main_img" src="https://img.overpic.net/images/d/s/b/xdsbjt23tza87zd8nfyc.png" alt="" title="" onmouseover="this.style.cursor='hand';" onclick="showrs()" style="border: 1px dashed #000000; padding: 2px; max-width:99%; width: auto; max-height:99%; height: auto;"> The strider-webhooks can't find bson .  i find windos and linux all throw out this error ! thank you very much

**Comment by knownasilya** [comment]
Notice line 19, the error is ignored and an alternative is used. This is a non issue and a red herring if something doesn't work for you.

What is the version of `strider` (not `strider-cli`)?

**Comment by strobox** [comment]
Hello. I have same issue.

**Comment by olivierb2** [comment]
+1

**Comment by knownasilya** [comment]
Closing since the bson issue is handled, there must be another error. I recommend giving 2.1.0 a try.
