### ISSUE TITLE
500 TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by Juliogdsilva** [Strider-CD/strider#1103]
am I having this error, any idea what it might be?

[Connect
500 TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
   at validateString (internal/validators.js:120:11)
   at resolve (path.js:980:7)
   at View.lookup (/var/www/strider/apps/strider/node_modules/express/lib/view.js:114:15)
   at new View (/var/www/strider/apps/strider/node_modules/express/lib/view.js:94:20)
   at Function.render (/var/www/strider/apps/strider/node_modules/express/lib/application.js:570:12)
   at ServerResponse.render (/var/www/strider/apps/strider/node_modules/express/lib/response.js:1012:7)
   at exports.emberIndex (/var/www/strider/apps/strider/dist-lib/routes/index.js:60:13)
   at Layer.handle [as handle_request] (/var/www/strider/apps/strider/node_modules/express/lib/router/layer.js:95:5)
   at next (/var/www/strider/apps/strider/node_modules/express/lib/router/route.js:137:13)
   at Route.dispatch (/var/www/strider/apps/strider/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/var/www/strider/apps/strider/node_modules/express/lib/router/layer.js:95:5)
   at /var/www/strider/apps/strider/node_modules/express/lib/router/index.js:281:22
   at param (/var/www/strider/apps/strider/node_modules/express/lib/router/index.js:354:14)
   at param (/var/www/strider/apps/strider/node_modules/express/lib/router/index.js:365:14)
   at Function.process_params (/var/www/strider/apps/strider/node_modules/express/lib/router/index.js:410:3)
   at next (/var/www/strider/apps/strider/node_modules/express/lib/router/index.js:275:10)
   at slashes (/var/www/strider/apps/strider/node_modules/connect-slashes/lib/connect-slashes.js:81:9)
   at Layer.handle [as handle_request] (/var/www/strider/apps/strider/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/var/www/strider/apps/strider/node_modules/express/lib/router/index.js:317:13)
   at /var/www/strider/apps/strider/node_modules/express/lib/router/index.js:284:7
   at Function.process_params (/var/www/strider/apps/strider/node_modules/express/lib/router/index.js:335:12)
   at next (/var/www/strider/apps/strider/node_modules/express/lib/router/index.js:275:10)
   at /var/www/strider/apps/strider/dist-lib/app.js:226:9
   at Layer.handle [as handle_request] (/var/www/strider/apps/strider/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/var/www/strider/apps/strider/node_modules/express/lib/router/index.js:317:13)
   at /var/www/strider/apps/strider/node_modules/express/lib/router/index.js:284:7
   at Function.process_params (/var/www/strider/apps/strider/node_modules/express/lib/router/index.js:335:12)
   at next (/var/www/strider/apps/strider/node_modules/express/lib/router/index.js:275:10)](url)

I tried everything, but I can't find the solution.

**Comment by knownasilya** [comment]
Try 2.4.11

I'll push a fix tonight.

**Comment by aldorado** [comment]
This is still an issue starting from v2.4.7 to strider_v2.4.13

There is no v2.4.11 release

**Comment by knownasilya** [comment]
v2.4.19 should work now.

**Comment by knownasilya** [comment]
Releases are on npm or via tags on github.
