### ISSUE TITLE
500 TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by aldorado** [Strider-CD/strider#1106]
This is still an issue, in all releases from v2.4.7 to strider_v2.4.13

Found no release 2.4.11 as mentioned in https://github.com/Strider-CD/strider/issues/1103

Stacktrace using strider_v2.4.13
```
2020-07-21T11:51:32.621Z - error: (node:21912) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
2020-07-21T11:51:32.657Z - error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at resolve (path.js:980:7)
    at View.lookup (/home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/view.js:114:15)
    at new View (/home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/view.js:94:20)
    at Function.render (/home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/response.js:1016:7)
    at exports.emberIndex (/home/aldorado/dev/inframove/cdci/strider/strider/apps/strider/dist-lib/routes/index.js:60:13)
    at Layer.handle [as handle_request] (/home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/router/layer.js:95:5)
    at /home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/router/index.js:281:22
    at param (/home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/router/index.js:354:14)
    at param (/home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/router/index.js:410:3)
    at next (/home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/router/index.js:275:10)
    at slashes (/home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/connect-slashes/1.4.0/node_modules/connect-slashes/lib/connect-slashes.js:81:9)
    at Layer.handle [as handle_request] (/home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/router/index.js:317:13)
    at /home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/router/index.js:335:12)
    at next (/home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/router/index.js:275:10)
    at /home/aldorado/dev/inframove/cdci/strider/strider/apps/strider/dist-lib/app.js:226:9
    at Layer.handle [as handle_request] (/home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/router/index.js:317:13)
    at /home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/router/index.js:335:12)
    at next (/home/aldorado/dev/inframove/cdci/strider/strider/common/temp/node_modules/.pnpm/registry.npmjs.org/express/4.17.0/node_modules/express/lib/router/index.js:275:10)
```

**Comment by knownasilya** [comment]
Reopened original issue

**Comment by chansdad** [comment]
What is the possible reason for this ? I installed the latest version and seeing this when i start strider and access the site on port 3000

**Comment by knownasilya** [comment]
@chansdad how did you install? With `npm install -g strider` or `git clone ...`?

**Comment by knownasilya** [comment]
v2.4.19 should work now.
