### ISSUE TITLE
Git Clone Failed with code 128 (Windows local)

### ISSUE THREAD

**Issue by damienhtw** [Strider-CD/strider#446]
After authorizing Github with my local version of strider, On running a test I'm getting the following error:

```
 environment 0ms
 prepare -1
$ git clone --recursive https://[username]:[password]@github.com/damienhtw/chat-client.git . github 11.5s -1
Cloning into '.'...
fatal: cannot create directory at 'app/teamwork_modules/chat-event-helpers/node_modules/gulp-coffee/node_modules/gulp-util/node_modules/lodash.template/node_modules/lodash.escape/node_modules/lodash._escapehtmlchar/node_modules': Filename too long
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

$  -1
An unexpected error occurred while executing this job. Please report at https://github.com/Strider-CD/strider/issues

Git clone failed with code 128

Error: Git clone failed with code 128
    at badCode (C:\Users\Administrator\AppData\Roaming\npm\node_modules\strider\node_modules\strider-git\worker.js:82:11)
    at updateCache (C:\Users\Administrator\AppData\Roaming\npm\node_modules\strider\node_modules\strider-git\worker.js:146:31)
    at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\strider\node_modules\strider-simple-runner\node_modules\strider-runner-core\lib\job.js:188:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Process.ChildProcess._handle.onexit (child_process.js:822:5)
Git clone failed with code 128
Error: Git clone failed with code 128
    at badCode (C:\Users\Administrator\AppData\Roaming\npm\node_modules\strider\node_modules\strider-git\worker.js:82:11)
    at updateCache (C:\Users\Administrator\AppData\Roaming\npm\node_modules\strider\node_modules\strider-git\worker.js:146:31)
    at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\strider\node_modules\strider-simple-runner\node_modules\strider-runner-core\lib\job.js:188:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Process.ChildProcess._handle.onexit (child_process.js:822:5)

```

Can't seem to find any real reason why the clone is failing.Any help on this would be much appreciated.

**Comment by razinbunsu** [comment]
Thanks guys `git config --global core.longpaths true` works for me.

**Comment by Samantha258** [comment]
Long Path Tool help me a lot when i have an issue like file deleting or renaming the file. Also good to use if file name and file extension is too long.
