### ISSUE TITLE
Add global SSH keys for all projects

### ISSUE THREAD

**Issue by nstaeger** [Strider-CD/strider#572]
Hi there,

I have a bunch of GitHub repositories I want Strider to deploy and test. But somehow this does not work as I hoped.

I wanted Strider to use the default SSH-keys that are in my user-folder `username/.ssh/` and which work in my commandline perfectly with Git. But somehow strider does not want them. When I provide the SSH-keys directly in the project-settings, strider is able to get the repository. But leaving them blank does not work and Strider outputs the following error:

```
$ git clone --recursive git@github.com:url.git . -b master

Cloning into '.'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

An unexpected error occurred while executing this job. Please report at https://github.com/Strider-CD/strider/issues

Git clone failed with code 500

Error: Git clone failed with code 500
    at badCode (/Users/admin/strider/node_modules/strider-git/worker.js:88:11)
    at updateCache (/Users/admin/strider/node_modules/strider-git/worker.js:152:31)
    at /Users/admin/strider/node_modules/strider-git/lib/index.js:99:5
    at Function.<anonymous> (/Users/admin/strider/node_modules/strider-git/node_modules/gitane/index.js:161:7)
    at next (/Users/admin/strider/node_modules/step/lib/step.js:51:23)
    at ChildProcess.<anonymous> (/Users/admin/strider/node_modules/strider-git/node_modules/gitane/index.js:151:9)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:95:17)
```

Running the same command in the terminal works perfect.

So my question is: Am I making something wrong here? Is this a bug? Do I need to set the keys for each project by hand or is there a way to provide one SSH-key for all projects?

Best

**Comment by kauegimenes** [comment]
+ 1 for this feature!

**Comment by rimusz** [comment]
+1 for this one too

**Comment by knownasilya** [comment]
Global as in to the user or for all users?

**Comment by rimusz** [comment]
all users please

**Comment by rimusz** [comment]
@knownasilya I see this one was not added to v1.7.0

**Comment by knownasilya** [comment]
No, a few items that were planned didn't make it due to lack of man power, but it's still planned for as soon as possible.

**Comment by rimusz** [comment]
any plans for this one go to the next release version?
