### ISSUE TITLE
Can't add github

### ISSUE THREAD

**Issue by hmrtk** [Strider-CD/strider#599]
When trying to add github, it prompts me for authorization but when going back to http://localhost:3000/auth/github/callback?code=XXX it generates the following error:

Express
500 TypeError: Cannot read property '0' of undefined
at makeAccount (/Users/Hamid/Developer/strider/node_modules/strider-github/lib/webapp.js:167:28)
at Strategy.validateAuth [as _verify](/Users/Hamid/Developer/strider/node_modules/strider-github/lib/webapp.js:152:26)
at /Users/Hamid/Developer/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/lib/strategy.js:188:22
at /Users/Hamid/Developer/strider/node_modules/strider-github/node_modules/passport-github/lib/strategy.js:109:5
at passBackControl (/Users/Hamid/Developer/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:126:9)
at IncomingMessage. (/Users/Hamid/Developer/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
at IncomingMessage.EventEmitter.emit (events.js:117:20)
at _stream_readable.js:920:16
at process._tickCallback (node.js:415:13)

**Comment by akamensky** [comment]
Oh hell why??? What is the reason for exposing my email publicly? To collect tons of spam there? What if my repo private, but I still need to have publicly exposed email???

**Comment by knownasilya** [comment]
@akamensky take that up with Github :smirk_cat: we have nothing to do with it.
