### ISSUE TITLE
Cannot clone git repository when used as package.json dependency

### ISSUE THREAD

**Issue by howarddierking** [Strider-CD/strider#621]
Hi - In my Node project, I'm referencing another project (internally via it's github repository URL). My package.json file looks similar to the following:

```
{
  ...
  "dependencies": {
    "request": "^2.45.0",
    "underscore": "^1.7.0",
    "my-utils": "git+ssh://git@github.com:my/node-utils.git#dev"
  },
  ...
}
```

Everything starts working as expected, until npm tries to resolve the git-based dependency. Then I get the following error.

```
npm ERR! git clone git@github.com:my/node-utils.git Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-my-node-utils-git-3fdbd8e2'...
npm ERR! git clone git@github.com:my/node-utils.git Host key verification failed.
npm ERR! git clone git@github.com:my/node-utils.git fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:my/node-utils.git 
npm ERR! git clone git@github.com:my/node-utils.git Please make sure you have the correct access rights
npm ERR! git clone git@github.com:my/node-utils.git and the repository exists.
npm ERR! Error: Command failed: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-my-node-utils-git-3fdbd8e2'...
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:637:15)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:743:16)
npm ERR!     at Socket.<anonymous> (child_process.js:956:11)
npm ERR!     at Socket.EventEmitter.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:466:12)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>
```

Is there something I need to do on my end to make this work? My assumption was that the same ssh key used to clone the project repo would be used to resolve the npm dependency, but that doesn't seem to be the case here.

thanks,

_howard

**Comment by Sridhararshanapally** [comment]
@howarddierking I am also facing the same error with NPM , did you able to figure out ?

**Comment by howarddierking** [comment]
Yes, the problem, IIRC, was related to key reuse on GitHub. We ended up using myget.org for private package hosting - has proven to be a reliable solution.

**Comment by IshanTiwari007** [comment]
Adding Public SSH Key to my GitHub account and installing the package via NPM through git Bash Worked for me !! Try this if works do let me know !!
