### ISSUE TITLE
Install Error on Ubuntu 14.04

### ISSUE THREAD

**Issue by tiny-dancer** [Strider-CD/strider#687]
May be my ignorance with linux but getting the following error when following the http://fosterelli.co/creating-a-private-ci-with-strider.html guide. 

bower install --config.interactive=false --allow-root && npm run build

Error: EACCES, permission denied '/home/strider/.config'
    at Object.fs.mkdirSync (fs.js:653:18)
    at sync (/usr/local/lib/node_modules/bower/node_modules/mkdirp/index.js:70:13)
    at Function.sync (/usr/local/lib/node_modules/bower/node_modules/mkdirp/index.js:76:24)
    at Object.create.all.get (/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:41:13)
    at Object.Configstore (/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/local/lib/node_modules/bower/node_modules/insight/lib/index.js:26:34)
    at ensureInsight (/usr/local/lib/node_modules/bower/lib/util/analytics.js:26:19)
    at Object.setup (/usr/local/lib/node_modules/bower/lib/util/analytics.js:43:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:72:11)
    at Module._compile (module.js:456:26)
npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "strider"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE

npm ERR! strider@1.6.0 postinstall: `bower install --config.interactive=false --allow-root && npm run build`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the strider@1.6.0 postinstall script 'bower install --config.interactive=false --allow-root && npm run build'.
npm ERR! This is most likely a problem with the strider package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install --config.interactive=false --allow-root && npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls strider
npm ERR! There is likely additional logging output above.

Any help is appreciated

**Comment by keyvanfatehi** [comment]
@tiny-dancer looks like a permission issue. is `/home/strider` writeable for the user from which you are issuing the command?

**Comment by tiny-dancer** [comment]
i would believe so i used root and sudo from another user.

**Comment by tiny-dancer** [comment]
@keyvanfatehi  i was able to bypass the problem by switching to the ubuntu nodejs-legacy and npm packages instead of chris-lea's nodejs ppa.  then subsequently had to install 4 or 5 dependecies that weren't found in the postBuildScripts triggered on npm install -g strider.

**Comment by tiny-dancer** [comment]
@keyvanfatehi piggy backing on that 'bypass' getting an infinite loop when running the upstart script:

```bash
2015-01-12T04:02:17.341Z - info: Using MongoDB URL: mongodb://strider:T1nYDanC3R@ds031681.mongolab.com:31681/strider-cd

Error: Cannot find module 'path-to-regexp'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/strider/lib/views-test.js:11:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
26865 died 8 null
26871 forked
```

**Comment by keyvanfatehi** [comment]
strange, sounds like a bumpy install. glad it is working now.

perhaps we should look into creating an ubuntu distribution for strider. we could very well embed node.js and npm right into the package and avoid this sort of thing.

**Comment by fernandoneto** [comment]
its not the firs time i see issue's installing strider with chris-lea's nodejs ppa.
@keyvanfatehi perhaps a short guide of dependencies is better than a linux distro.
i can help if you want.

**Comment by knownasilya** [comment]
The version of npm is too low, use 1.4, but 2.x is recommended.

**Comment by fernandoneto** [comment]
thats not a problem with npm, i have the same version without issues...... :+1:

**Comment by knownasilya** [comment]
So is the issue global modules permissions? We've had plenty of those around here. I think an optimal solution was found in one of those issues.

**Comment by knownasilya** [comment]
Really it seems like poor installations, which really goes back to npm ultimately. With npm if you miss an error and think your good, another npm install will not help so much, unless you delete the node_modules folder.

Usually it's a bad install, or an install that was ctrl-c'd.
