### ISSUE TITLE
Force pushes confuse Git caching

### ISSUE THREAD

**Issue by doublerebel** [Strider-CD/strider#701]
When using `git push --force` to Strider, the `git pull` to update the cache fails with Code 500:

```sh
# restored code from cache gitlab  -1
$ git reset --hard gitlab 93ms -1
HEAD is now at <redacted>
$ git pull gitlab 586ms -1
From ssh://gitlab.../app
 <redacted>  (forced update)

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <strider@.co>) not allowed
$  -1
An unexpected error occurred while executing this job. Please report at https://github.com/Strider-CD/strider/issues

Git pull failed with code 500

Error: Git pull failed with code 500
    at badCode (/home/strider/strider/node_modules/strider-gitlab/node_modules/strider-git/worker.js:88:11)
    at updateCache (/home/strider/strider/node_modules/strider-gitlab/node_modules/strider-git/worker.js:152:31)
    at /home/strider/strider/node_modules/strider-gitlab/node_modules/strider-git/lib/index.js:106:5
    at Function.<anonymous> (/home/strider/strider/node_modules/strider-gitlab/node_modules/strider-git/node_modules/gitane/index.js:161:7)
    at next (/home/strider/strider/node_modules/step/lib/step.js:51:23)
    at ChildProcess.<anonymous> (/home/strider/strider/node_modules/strider-gitlab/node_modules/strider-git/node_modules/gitane/index.js:151:9)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```

Those values are set for the "strider" user which strider runs under, and I've also tried setting them with "custom scripts" plugin during the environment setup, but nothing has worked yet.  I must clear the cache and retest.

**Comment by knownasilya** [comment]
Is this repeatable? Can you try with a different project and maybe with github.

**Comment by doublerebel** [comment]
It seems to be an issue with any lib using [Strider-CD/strider-git](//github.com/Strider-CD/strider-git).  There's an easy fix by swapping the command order and not using `git pull`, since `git pull` will try to merge a branch with diverging history.  PR made.
