### ISSUE TITLE
TypeError: Object #<Object> has no method 'collaborator_invite_new'

### ISSUE THREAD

**Issue by leutrimhusaj** [Strider-CD/strider#709]
This is what i get when adding an collaborator to an existing project.

strider stderr | TypeError: Object #<Object> has no method 'collaborator_invite_new'
    at Object.exports.send_invite_collaborator_new_user (/opt/strider/src/lib/email.js:115:24)
    at Promise.<anonymous> (/opt/strider/src/lib/routes/api/collaborators/api.js:48:10)
    at Promise.<anonymous> (/opt/strider/src/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.EventEmitter.emit (events.js:98:17)
    at Promise.emit (/opt/strider/src/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/opt/strider/src/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at handleSave (/opt/strider/src/node_modules/mongoose/lib/model.js:133:13)
    at /opt/strider/src/node_modules/mongoose/lib/utils.js:408:16
    at /opt/strider/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection/core.js:128:9
    at /opt/strider/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1174:7
    at /opt/strider/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at Server.Base._callHandler (/opt/strider/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /opt/strider/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:487:18
    at MongoReply.parseBody (/opt/strider/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/opt/strider/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)
    at EventEmitter.emit (events.js:95:17)

I think the problem is:

+  var body_text = text.collaborator_invite_new(jade_variables);
+  var body_html = html.collaborator_invite_new(jade_variables);

But the template name is collaborator_invite_new_user, is this correct?

**Comment by knownasilya** [comment]
Thanks for letting us know! Will have a look at it.

**Comment by knownasilya** [comment]
@leutrimhusaj can you try out master and see if that fixed your problem?

**Comment by leutrimhusaj** [comment]
@knownasilya  I have changed the same code locally in my strider version and it works!
