### ISSUE TITLE
413 Error: request entity too large

### ISSUE THREAD

**Issue by kadut** [Strider-CD/strider#722]
Occasionally and when the merged PR is big, Strider response to the GitHub webhook is the following:

```html
<html>
  <head>
    <meta charset='utf-8'>
    <title>Error: request entity too large</title>
    <style>* {
  margin: 0;
  padding: 0;
  outline: 0;
}

body {
  padding: 80px 100px;
  font: 13px "Helvetica Neue", "Lucida Grande", "Arial";
  background: #ECE9E9 -webkit-gradient(linear, 0% 0%, 0% 100%, from(#fff), to(#ECE9E9));
  background: #ECE9E9 -moz-linear-gradient(top, #fff, #ECE9E9);
  background-repeat: no-repeat;
  color: #555;
  -webkit-font-smoothing: antialiased;
}
h1, h2 {
  font-size: 22px;
  color: #343434;
}
h1 em, h2 em {
  padding: 0 5px;
  font-weight: normal;
}
h1 {
  font-size: 60px;
}
h2 {
  margin-top: 10px;
}
ul li {
  list-style: none;
}
#stacktrace {
  margin-left: 60px;
}
</style>
  </head>
  <body>
    <div id="wrapper">
      <h1>Connect</h1>
      <h2><em>413</em> Error: request entity too large</h2>
      <ul id="stacktrace"><li> &nbsp; &nbsp;at makeError (/opt/strider/src/node_modules/body-parser/node_modules/raw-body/index.js:184:15)</li><li> &nbsp; &nbsp;at module.exports (/opt/strider/src/node_modules/body-parser/node_modules/raw-body/index.js:40:15)</li><li> &nbsp; &nbsp;at read (/opt/strider/src/node_modules/body-parser/lib/read.js:62:3)</li><li> &nbsp; &nbsp;at urlencodedParser (/opt/strider/src/node_modules/body-parser/lib/types/urlencoded.js:84:5)</li><li> &nbsp; &nbsp;at Layer.handle [as handle_request] (/opt/strider/src/node_modules/express/lib/router/layer.js:82:5)</li><li> &nbsp; &nbsp;at trim_prefix (/opt/strider/src/node_modules/express/lib/router/index.js:302:13)</li><li> &nbsp; &nbsp;at /opt/strider/src/node_modules/express/lib/router/index.js:270:7</li><li> &nbsp; &nbsp;at Function.proto.process_params (/opt/strider/src/node_modules/express/lib/router/index.js:321:12)</li><li> &nbsp; &nbsp;at next (/opt/strider/src/node_modules/express/lib/router/index.js:261:10)</li><li> &nbsp; &nbsp;at bodySetter (/opt/strider/src/lib/middleware.js:44:3)</li><li> &nbsp; &nbsp;at Layer.handle [as handle_request] (/opt/strider/src/node_modules/express/lib/router/layer.js:82:5)</li><li> &nbsp; &nbsp;at trim_prefix (/opt/strider/src/node_modules/express/lib/router/index.js:302:13)</li><li> &nbsp; &nbsp;at /opt/strider/src/node_modules/express/lib/router/index.js:270:7</li><li> &nbsp; &nbsp;at Function.proto.process_params (/opt/strider/src/node_modules/express/lib/router/index.js:321:12)</li><li> &nbsp; &nbsp;at next (/opt/strider/src/node_modules/express/lib/router/index.js:261:10)</li><li> &nbsp; &nbsp;at logger (/opt/strider/src/node_modules/morgan/index.js:136:5)</li></ul>
    </div>
  </body>
</html>
```

This has happened several times. Do you have any idea how we can increase the max. request size?

Thanks!

**Comment by knownasilya** [comment]
This should be fixed in master, see the [Additional Configurations](https://github.com/Strider-CD/strider#additional-configurations) section for configuration.
