### ISSUE TITLE
Cannot connect to Bitbucket/Github with local strider installation in Safari Browser

### ISSUE THREAD

**Issue by amanmohla** [Strider-CD/strider#737]
This might be strange as it doesn't looks like a browser based issue, but when I try access my local strider installation in Safari browser, I am unable to connect with Bitbucket or Github. I get the following error in my console. 
<pre><code>
GET /projects 200 49.521 ms - -
GET /scripts/account-plugins-compiled.js 200 13.825 ms - 932
GET /scripts/plugin-config-compiled.js 200 28.935 ms - -
GET /scripts/plugin-status-compiled.js 304 16.943 ms - -
GET /ext/bitbucket/oauth 302 1857.991 ms - 0
2015-02-25T09:06:57.883Z - error: Error: failed to find request token in session
    at Strategy.OAuthStrategy.authenticate (/usr/local/lib/node_modules/strider/node_modules/strider-bitbucket/node_modules/passport-bitbucket/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js:124:54)
    at attempt (/usr/local/lib/node_modules/strider/node_modules/passport/lib/middleware/authenticate.js:341:16)
    at authenticate (/usr/local/lib/node_modules/strider/node_modules/passport/lib/middleware/authenticate.js:342:7)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/strider/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/lib/node_modules/strider/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/usr/local/lib/node_modules/strider/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/strider/node_modules/express/lib/router/layer.js:82:5)
    at /usr/local/lib/node_modules/strider/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/usr/local/lib/node_modules/strider/node_modules/express/lib/router/index.js:321:12)
    at next (/usr/local/lib/node_modules/strider/node_modules/express/lib/router/index.js:261:10)
    at /usr/local/lib/node_modules/strider/lib/app.js:282:5
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/strider/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/usr/local/lib/node_modules/strider/node_modules/express/lib/router/index.js:302:13)
    at /usr/local/lib/node_modules/strider/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/usr/local/lib/node_modules/strider/node_modules/express/lib/router/index.js:321:12)
    at next (/usr/local/lib/node_modules/strider/node_modules/express/lib/router/index.js:261:10)
GET /ext/bitbucket/oauth/callback?oauth_verifier=8362420866&oauth_token=b6FPL54nQEt9hBTur6 500 9.655 ms - -
GET /projects 302 5.489 ms - 68
</code></pre>

However I am able to authenticate with Bitbucket and Github when I am using Chrome.

**Comment by knownasilya** [comment]
@amanmohla what do you mean  by "connect to bitbucket"? Are you trying to add a project?

Steps to reproduce would be appreciated.

**Comment by leonfs** [comment]
I'm experiencing the same issue but not just in Safari, also in Chrome. 

I'm using the dockerized version from quay.io

In my case, I did manage to add a project from BitBucket, but at some point stopped working. 

I had to manually remove projects from the DB. When I tried to add the project again, this connection problem to BitBucket started happening. Probably was the same problem that caused the build to stop working. 

I'm going to provide more details tomorrow morning. It's 2 AM here and I'm knackered. But I confirm that I'm seeing the same exception.

**Comment by knownasilya** [comment]
@leonfs can you try it without the dockerized version, since it's not exactly stable.

**Comment by donaldpcook** [comment]
If you're doing this locally, make sure you're using localhost (instead of 0.0.0.0 or something else) in your browser or change the SERVER_NAME to the correct IP. Otherwise you'll get this error.

**Comment by michaelmior** [comment]
Closing due to lack of response. Feel free to respond with additional details if this is still a problem and this can be reopened.
