### ISSUE TITLE
Install issue on ubuntu related to bower post install task

### ISSUE THREAD

**Issue by dionridley** [Strider-CD/strider#751]
I've installed strider with no issues on my Mac but when attempting to install it on ubuntu I'm getting the following issue during postinstall.  I'm using sudo for the install but its appears to be trying to write to <myaccount> below.  Is there something I'm doing wrong or a fix for this?

==========
> strider@1.6.4 postinstall /usr/lib/node_modules/strider
> bower install --allow-root && npm run build

bower                           EACCES EACCES: permission denied, mkdir '/home/<myaccount>/.cache/bower/registry/bower.herokuapp.com/lookup'

Stack trace:
Error: EACCES: permission denied, mkdir '/home/<myaccount>/.cache/bower/registry/bower.herokuapp.com/lookup'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:793:18)
    at Function.sync (/usr/lib/node_modules/strider/node_modules/bower/node_modules/bower-registry-client/node_modules/mkdirp/index.js:55:12)
    at new Cache (/usr/lib/node_modules/strider/node_modules/bower/node_modules/bower-registry-client/lib/util/Cache.js:21:16)
    at RegistryClient.<anonymous> (/usr/lib/node_modules/strider/node_modules/bower/node_modules/bower-registry-client/lib/lookup.js:163:35)
    at Array.forEach (native)
    at RegistryClient.initCache (/usr/lib/node_modules/strider/node_modules/bower/node_modules/bower-registry-client/lib/lookup.js:150:34)
    at RegistryClient._initCache (/usr/lib/node_modules/strider/node_modules/bower/node_modules/bower-registry-client/Client.js:62:27)
    at new RegistryClient (/usr/lib/node_modules/strider/node_modules/bower/node_modules/bower-registry-client/Client.js:16:10)
    at new PackageRepository (/usr/lib/node_modules/strider/node_modules/bower/lib/core/PackageRepository.js:17:28)

Console trace:
Trace
    at StandardRenderer.error (/usr/lib/node_modules/strider/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/usr/lib/node_modules/strider/node_modules/bower/bin/bower:110:22)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:166:7)
    at Logger.emit (/usr/lib/node_modules/strider/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/strider/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/usr/lib/node_modules/strider/node_modules/bower/node_modules/q/q.js:797:24)
    at /usr/lib/node_modules/strider/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/usr/lib/node_modules/strider/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/strider/node_modules/bower/node_modules/q/q.js:741:41)

System info:
Bower version: 1.3.12
Node version: 1.6.2
OS: Linux 3.2.0-31-virtual x64
npm ERR! Linux 3.2.0-31-virtual
npm ERR! argv "/usr/bin/iojs" "/usr/bin/npm" "install" "-g" "strider"
npm ERR! node v1.6.2
npm ERR! npm  v2.7.1
npm ERR! code ELIFECYCLE

npm ERR! strider@1.6.4 postinstall: `bower install --allow-root && npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strider@1.6.4 postinstall script 'bower install --allow-root && npm run build'.
npm ERR! This is most likely a problem with the strider package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install --allow-root && npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls strider
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/bin/npm-debug.log

**Comment by knownasilya** [comment]
Sounds like a bower issue. Is this in heroku?

FYI, there are many issues with npm and using sudo, especially on Ubunut.

**Comment by dionridley** [comment]
It was on an AWS ubuntu 12.x box (not heroku). But yeah, it looks like it is related to bower from a thread I found investigating.  Bower does something with caching the user and then always tries to use that user's home.  I cleaned up the hidden files and re-installing io.js for a fresh setup and it installed properly.

**Comment by knownasilya** [comment]
@dionridley I just pushed a commit to master that works with io.js.

Also, I'm planning on not requiring the end user to do bower installs. Once I have some time :+1:

**Comment by bmustata** [comment]
Only worked after I installed strider like a node.js app without -g flag.

**Comment by knownasilya** [comment]
@bmustata that should change in the next release.
