### ISSUE TITLE
Version of mongoose in Strider does not work with MongoDB 3.x

### ISSUE THREAD

**Issue by dionridley** [Strider-CD/strider#752]
When trying to addUser or start server getting the following error

==================
17647 forked

##############################################################
#
#   !!! MONGOOSE WARNING !!!
#
#   This is an UNSTABLE release of Mongoose.
#   Unstable releases are available for preview/testing only.
#   DO NOT run this in production.
#
##############################################################

2015-03-27T16:54:43.099Z - info: stubbing smtp..
2015-03-27T16:54:43.714Z - info: Using MongoDB URL: mongodb://localhost/strider-foss
2015-03-27T16:54:43.791Z - warn: No SMTP creds - forgot password flow will not work
/usr/local/lib/node_modules/strider/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;      
              ^
TypeError: Cannot read property 'length' of undefined
    at processResults (/usr/local/lib/node_modules/strider/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1581:31)
    at /usr/local/lib/node_modules/strider/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1619:20
    at /usr/local/lib/node_modules/strider/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1157:7
    at /usr/local/lib/node_modules/strider/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1890:9
    at Server.Base._callHandler (/usr/local/lib/node_modules/strider/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:448:41)
    at /usr/local/lib/node_modules/strider/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:481:18
    at MongoReply.parseBody (/usr/local/lib/node_modules/strider/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/usr/local/lib/node_modules/strider/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:439:20)
    at emitOne (events.js:77:13)
    at emit (events.js:166:7)
    at null.<anonymous> (/usr/local/lib/node_modules/strider/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
    at emitTwo (events.js:87:13)
    at emit (events.js:169:7)
    at Socket.<anonymous> (/usr/local/lib/node_modules/strider/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:439:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
17647 died 1 null

======================

I manually updated the package.json for strider to use the 4.x version of Mongoose and it appears to be working correctly.  I'm not sure the implications for older versions of MongoDB but this resolved my issue.

**Comment by knownasilya** [comment]
@dionridley I just tried it with mongoose 4.0.0 and get that error. What version did you have previously?

**Comment by knownasilya** [comment]
@dionridley 3.8.x works fine. I'm hardcoding that now.

**Comment by knownasilya** [comment]
@dionridley released 1.6.5 with all of the latest fixes, including this, io.js support, some others, see the release notes.

**Comment by niallo** [comment]
Awesome work Ilya!

On Fri, Mar 27, 2015 at 11:33 AM, Ilya Radchenko <notifications@github.com>
wrote:

> @dionridley <https://github.com/dionridley> released 1.6.5 with all of
> the latest fixes, including this, io.js support, some others, see the
> release notes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Strider-CD/strider/issues/752#issuecomment-87045497>.
>



-- 
Niall O'Higgins
W: http://niallohiggins.com
E: n@niallo.me
T: @niallohiggins

**Comment by dionridley** [comment]
Thanks.  Appreciate you responding and addressing issues quickly!

**Comment by cusspvz** [comment]
seeing this on `quay.io/keyvanfatehi/strider:1.6.0-pre.2`

**Comment by knownasilya** [comment]
This has been fixed since, and that version of the image is old.
