### ISSUE TITLE
Linking a github account still breaks if your email is set to private on github

### ISSUE THREAD

**Issue by dionridley** [Strider-CD/strider#753]
When first trying strider I had this issue when I tried to link my github account.  I resolved it by going into github and making my email address public (which I don't want to do) and then after linking the account with Strider switching it back to private.  Once that initial check happens no more issues. It is discussed here but the problem still occurs in the latest version.

https://github.com/Strider-CD/strider-github/issues/25

Logging this so if its left as a known issue we at least notify the user of this trick/tip instead of a 500.  I believe you might only be able to test this with a new user.

======================
Connect
500 TypeError: Cannot read property '0' of undefined
   at makeAccount (/usr/local/lib/node_modules/strider/node_modules/strider-github/lib/webapp.js:167:28)
   at Strategy.validateAuth [as _verify] (/usr/local/lib/node_modules/strider/node_modules/strider-github/lib/webapp.js:152:26)
   at /usr/local/lib/node_modules/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/lib/strategy.js:188:22
   at /usr/local/lib/node_modules/strider/node_modules/strider-github/node_modules/passport-github/lib/strategy.js:109:5
   at passBackControl (/usr/local/lib/node_modules/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:126:9)
   at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
   at emitNone (events.js:72:20)
   at IncomingMessage.emit (events.js:163:7)
   at _stream_readable.js:891:16
   at process._tickDomainCallback (node.js:388:13)

**Comment by knownasilya** [comment]
This is documented in strider-github and if you updates the plugins, under admin/ plugins the error is clear

**Comment by knownasilya** [comment]
Fixed, just make sure to update your plugins by going to "Admin" and then "Plugins" from the app. Update all of the plugins there. I'm going to add a note about upgrading plugins to the readme, at least until it happens automatically on first start.
