### ISSUE TITLE
Cant get Repos from Github

### ISSUE THREAD

**Issue by devotox** [Strider-CD/strider#811]
![screenshot 2015-06-17 11 54 57](https://cloud.githubusercontent.com/assets/2064846/8205359/cb7e55f0-14e7-11e5-9bf4-fcaa29249a5a.png)

**Comment by oliversalzburg** [comment]
@devotox Is there anything in the console in the browser's DevTools?

**Comment by knownasilya** [comment]
What does it look like when you select the github account tab?

**Comment by stampfl** [comment]
For me there is nothing in the console. The Github account shows my username and links back to my profile.

![github](https://cloud.githubusercontent.com/assets/778277/8317538/2f53c176-19b3-11e5-95aa-87131b09b06f.jpg)

**Comment by knownasilya** [comment]
Thanks @stampfl!

**Comment by oliversalzburg** [comment]
@devotox @stampfl Can you provide the strider log output?

When you receive `Failed to refresh repositories: [object Object]` the full error should be logged on the strider backend. This should give us a clear picture of what's going wrong.

**Comment by knownasilya** [comment]
It might be a clientside error..

**Comment by oliversalzburg** [comment]
@knownasilya The error is probably originating from https://github.com/Strider-CD/strider/blob/187ba1607452cbd8c6736719ddb320b62a5c6338/lib/routes/projects.js#L98

**Comment by stampfl** [comment]
The error is coming from the back end. Here is the entire log at ~/.pm2/logs/strider-error-0.log
I've already resolved the missing email mentioned in the log.
```
fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EACCES, permission denied '/opt/strider/.restart'
    at Object.fs.openSync (fs.js:439:18)
    at openThenF (/opt/strider/node_modules/strider-cli/node_modules/touch/touch.js:76:40)
    at touch_ (/opt/strider/node_modules/strider-cli/node_modules/touch/touch.js:69:10)
    at optionsRef (/opt/strider/node_modules/strider-cli/node_modules/touch/touch.js:41:28)
    at touch (/opt/strider/node_modules/strider-cli/node_modules/touch/touch.js:65:10)
    at Function.touch.touchSync.touch.sync (/opt/strider/node_modules/strider-cli/node_modules/touch/touch.js:6:10)
    at restart (/opt/strider/node_modules/strider-cli/resilient.js:9:13)
    at /opt/strider/lib/routes/admin/plugins/index.js:31:7
    at /opt/strider/node_modules/strider-cli/plugin_manager/install_plugin.js:45:17
    at ChildProcess.<anonymous> (/opt/strider/node_modules/strider-cli/plugin_manager/npm.js:19:18)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
2015-06-22T22:51:56.061Z - error: Error: You need to enter your email address into Github.
    at makeAccount (/opt/strider/node_modules/strider-github/lib/webapp.js:166:11)
    at Strategy.validateAuth [as _verify] (/opt/strider/node_modules/strider-github/lib/webapp.js:158:26)
    at /opt/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/lib/strategy.js:188:22
    at /opt/strider/node_modules/strider-github/node_modules/passport-github/lib/strategy.js:109:5
    at passBackControl (/opt/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:125:9)
    at IncomingMessage.<anonymous> (/opt/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:142:7)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
Mon, 22 Jun 2015 22:56:32 GMT express deprecated res.send(status): Use res.sendStatus(status) instead at lib/routes/api/account.js:57:15
2015-06-22T23:11:28.803Z - error: Error: You need to enter your email address into Github.
    at makeAccount (/opt/strider/node_modules/strider-github/lib/webapp.js:166:11)
    at Strategy.validateAuth [as _verify] (/opt/strider/node_modules/strider-github/lib/webapp.js:158:26)
    at /opt/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/lib/strategy.js:188:22
    at /opt/strider/node_modules/strider-github/node_modules/passport-github/lib/strategy.js:109:5
    at passBackControl (/opt/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:125:9)
    at IncomingMessage.<anonymous> (/opt/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:142:7)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
2015-06-22T23:21:11.575Z - error: Error: You need to enter your email address into Github.
    at makeAccount (/opt/strider/node_modules/strider-github/lib/webapp.js:166:11)
    at Strategy.validateAuth [as _verify] (/opt/strider/node_modules/strider-github/lib/webapp.js:158:26)
    at /opt/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/lib/strategy.js:188:22
    at /opt/strider/node_modules/strider-github/node_modules/passport-github/lib/strategy.js:109:5
    at passBackControl (/opt/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:125:9)
    at IncomingMessage.<anonymous> (/opt/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:142:7)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
2015-06-23T00:08:51.220Z - error: job.prepare - error opening/processing project's `strider.json` file:  [Error: not implemented]
2015-06-23T00:13:17.869Z - error: job.prepare - error opening/processing project's `strider.json` file:  [Error: not implemented]
Tue, 23 Jun 2015 00:13:37 GMT express deprecated res.send(status): Use res.sendStatus(status) instead at lib/routes/api/account.js:57:15
2015-06-23T20:04:38.394Z - error: job.prepare - error opening/processing project's `strider.json` file:  [Error: not implemented]
2015-06-23T20:07:17.269Z - error: job.prepare - error opening/processing project's `strider.json` file:  [Error: not implemented]
2015-06-23T20:07:40.581Z - error: job.prepare - error opening/processing project's `strider.json` file:  [Error: not implemented]
```

**Comment by knownasilya** [comment]
It didn't restart your instance after update, since the touch failed.

**Comment by stampfl** [comment]
Working! It was a permissions issue. Only some of the folders (like node_modules) could be modified by the app user. 

Any suggestions for permissions levels for this project? I'm deploying with puppet and running with a dedicated user. In any case, I'm good now. Thanks for your help!

**Comment by knownasilya** [comment]
@devotox what about you? :smile:

**Comment by devotox** [comment]
@knownasilya I apologize it took so long to get back to you. But yes i do believe it was a permissions issue and i am able to see my github repos now but when trying to add as a project i get this

015-07-03T12:16:06.095Z - error: TypeError: Cannot assign to read only property '_locals' of 404
    at ServerResponse.render (/Users/devonte/Documents/Doctify/platform/strider/node_modules/express/lib/response.js:952:16)
    at custom404 (/Users/devonte/Documents/Doctify/platform/strider/lib/middleware.js:80:7)
    at Layer.handle [as handle_request] (/Users/devonte/Documents/Doctify/platform/strider/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/devonte/Documents/Doctify/platform/strider/node_modules/express/lib/router/index.js:312:13)
    at /Users/devonte/Documents/Doctify/platform/strider/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/devonte/Documents/Doctify/platform/strider/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/devonte/Documents/Doctify/platform/strider/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle [as handle_request] (/Users/devonte/Documents/Doctify/platform/strider/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/Users/devonte/Documents/Doctify/platform/strider/node_modules/express/lib/router/index.js:312:13)
    at /Users/devonte/Documents/Doctify/platform/strider/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/devonte/Documents/Doctify/platform/strider/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/devonte/Documents/Doctify/platform/strider/node_modules/express/lib/router/index.js:271:10)
    at slashes (/Users/devonte/Documents/Doctify/platform/strider/node_modules/connect-slashes/lib/connect-slashes.js:81:9)
    at Layer.handle [as handle_request] (/Users/devonte/Documents/Doctify/platform/strider/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/devonte/Documents/Doctify/platform/strider/node_modules/express/lib/router/index.js:312:13)
    at /Users/devonte/Documents/Doctify/platform/strider/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/devonte/Documents/Doctify/platform/strider/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/devonte/Documents/Doctify/platform/strider/node_modules/express/lib/router/index.js:271:10)
    at /Users/devonte/Documents/Doctify/platform/strider/lib/app.js:265:5
    at Layer.handle [as handle_request] (/Users/devonte/Documents/Doctify/platform/strider/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/devonte/Documents/Doctify/platform/strider/node_modules/express/lib/router/index.js:312:13)
    at /Users/devonte/Documents/Doctify/platform/strider/node_modules/express/lib/router/index.js:280:7
2015-07-03T12:16:11.209Z - info: Fetching projects...
2015-07-03T12:16:13.426Z - info: Fetching projects...
2015-07-03T12:16:13.519Z - info: [ null ]
2015-07-03T12:16:13.546Z - info: Saved repo cache
2015-07-03T12:16:15.663Z - info: [ null ]
2015-07-03T12:16:15.691Z - info: Saved repo cache
2015-07-03T12:16:22.987Z - info: Fetching projects...
2015-07-03T12:16:25.237Z - info: [ null ]
2015-07-03T12:16:25.263Z - info: Saved repo cache
2015-07-03T12:16:39.736Z - info: Bad status code: 404
2015-07-03T12:16:39.739Z - info: Error: Bad status code: 404
    at Request._callback (/Users/devonte/Documents/Doctify/platform/strider/node_modules/strider-github/lib/api.js:55:26)
    at Request.self.callback (/Users/devonte/Documents/Doctify/platform/strider/node_modules/strider-github/node_modules/request/request.js:129:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/devonte/Documents/Doctify/platform/strider/node_modules/strider-github/node_modules/request/request.js:873:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/devonte/Documents/Doctify/platform/strider/node_modules/strider-github/node_modules/request/request.js:824:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
2015-07-03T12:17:11.084Z - info: Bad status code: 404
2015-07-03T12:17:11.085Z - info: Error: Bad status code: 404
    at Request._callback (/Users/devonte/Documents/Doctify/platform/strider/node_modules/strider-github/lib/api.js:55:26)
    at Request.self.callback (/Users/devonte/Documents/Doctify/platform/strider/node_modules/strider-github/node_modules/request/request.js:129:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/devonte/Documents/Doctify/platform/strider/node_modules/strider-github/node_modules/request/request.js:873:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/devonte/Documents/Doctify/platform/strider/node_modules/strider-github/node_modules/request/request.js:824:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by markulf** [comment]
I get a similar error message:

```
Error creating project for repo mitls/mitls-fstar: {"results":[],"status":"error","errors":[{"code":500,"reason":"Failed to setup repo: Bad status code: 404"}]}
```

Any solution for this? Strangely I get it only with some of my git projects but not with others, no clear pattern, some private repos work, others don't.

**Comment by knownasilya** [comment]
It would really help if you could figure out the similarities so we can reproduce the issue.

**Comment by markulf** [comment]
I currently suspect that it is related to not having admin rights for the relevant GitHub projects. Can confirm once I get those rights and the problem goes away. 

So it may be just an issue of not so human readable error messages.

**Comment by oliversalzburg** [comment]
@markulf Importing a project into strider will register webhooks with the project, which requires admin rights. So, your assumptions are probably correct.

**Comment by markulf** [comment]
Thanks I can confirm this now, it worked once I got more rights. 

A quick question, though I am looking for more information, and maybe this is a feature request: Can these webhooks also be triggered by other GitHub projects to reflect dependencies, i.e. my project depends on another GitHub project and I want to be notified when it gets broken by changes there. 

Even if this in principle works, there seems to be the practical problem of setting up the appropriate shared secrets.

**Comment by saraf** [comment]
There is perhaps a key in the first screenshot posted 
the error message - 
Failed to refresh repositories [Object object]

We actually do not receive an error, but an object parsed from JSON.

**Comment by knownasilya** [comment]
Looks like the OPs issue was with Bitbucket. Might have to make the changes there as well?

**Comment by knownasilya** [comment]
@markulf could you submit your feature request as a separate issue, with a little more detail and a use case? Thanks!

**Comment by markulf** [comment]
Thanks, will do once I understand the use case better. Currently trying to work around it with git pre_post hooks.
