### ISSUE TITLE
Just tried to update/rebuild master and got a babel error

### ISSUE THREAD

**Issue by notbrain** [Strider-CD/strider#834]
> [BABEL] Note: The code generator has deoptimised the styling of "/home/ubuntu/strider/vendor/CodeMirror/js/codemirror.js" as it exceeds the max of "100KB".
SyntaxError: /home/ubuntu/strider/client/ansi/filters/ansi.js: Octal literal in strict mode (85:31)
  83 |     if (matchingControl !== null) {

    $ npm run build

    > strider@1.6.6 build /home/ubuntu/strider
    > npm run pre && npm run styles && browserify -t babelify -e client/app.js -o dist/scripts/app.js

    > strider@1.6.6 pre /home/ubuntu/strider
    > mkdirp dist/scripts dist/styles

    > strider@1.6.6 styles /home/ubuntu/strider
    > lessc client/styles/strider.less > dist/styles/styles.css

    [BABEL] Note: The code generator has deoptimised the styling of "/home/ubuntu/strider/vendor/CodeMirror/js/codemirror.js" as it exceeds the max of "100KB".
    SyntaxError: /home/ubuntu/strider/client/ansi/filters/ansi.js: Octal literal in strict mode (85:31)
      83 |     if (matchingControl !== null) {
      84 |       /* jshint ignore:start */
    > 85 |       if (matchingControl === '\033' && str[i] === '\[') {
         |                                ^
      86 |         //
      87 |         // We've matched full control code. Lets start matching formating data.
      88 |         //
        at Parser.pp.raise (/home/ubuntu/strider/node_modules/babelify/node_modules/babel-core/lib/acorn/src/location.js:80:13)
        at Parser.pp.readEscapedChar (/home/ubuntu/strider/node_modules/babelify/node_modules/babel-core/lib/acorn/src/tokenize.js:708:16)
        at Parser.pp.readString (/home/ubuntu/strider/node_modules/babelify/node_modules/babel-core/lib/acorn/src/tokenize.js:607:19)
        at Parser.pp.getTokenFromCode (/home/ubuntu/strider/node_modules/babelify/node_modules/babel-core/lib/acorn/src/tokenize.js:394:19)
        at Parser.pp.readToken (/home/ubuntu/strider/node_modules/babelify/node_modules/babel-core/lib/acorn/src/tokenize.js:117:15)
        at Parser.<anonymous> (/home/ubuntu/strider/node_modules/babelify/node_modules/babel-core/node_modules/acorn-jsx/inject.js:399:22)
        at Parser.readToken (/home/ubuntu/strider/node_modules/babelify/node_modules/babel-core/lib/acorn/plugins/flow.js:696:22)
        at Parser.pp.nextToken (/home/ubuntu/strider/node_modules/babelify/node_modules/babel-core/lib/acorn/src/tokenize.js:109:71)
        at Parser.pp.next (/home/ubuntu/strider/node_modules/babelify/node_modules/babel-core/lib/acorn/src/tokenize.js:58:8)
        at Parser.pp.parseExprOp (/home/ubuntu/strider/node_modules/babelify/node_modules/babel-core/lib/acorn/src/expression.js:189:12)

    npm ERR! Linux 3.13.0-48-generic
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
    npm ERR! node v0.12.4
    npm ERR! npm  v2.10.1
    npm ERR! code ELIFECYCLE
    npm ERR! strider@1.6.6 build: `npm run pre && npm run styles && browserify -t babelify -e client/app.js -o dist/scripts/app.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the strider@1.6.6 build script 'npm run pre && npm run styles && browserify -t babelify -e client/app.js -o dist/scripts/app.js'.
    npm ERR! This is most likely a problem with the strider package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     npm run pre && npm run styles && browserify -t babelify -e client/app.js -o dist/scripts/app.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls strider
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/ubuntu/strider/npm-debug.log

**Comment by knownasilya** [comment]
Give master a try again. Not sure if the change is correct. I read this 

> Note that octal escapes have been deprecated in ES5

https://mathiasbynens.be/notes/javascript-escapes#hexadecimal

**Comment by notbrain** [comment]
WFM.
