### ISSUE TITLE
plugins -view crash

### ISSUE THREAD

**Issue by jupe** [Strider-CD/strider#852]
Every time when I try to open plugins -page, I just get error view:
![image](https://cloud.githubusercontent.com/assets/3822425/9568566/093104da-4f56-11e5-9279-259c00e7a279.png)

Server log says:
```
2015-08-30T17:28:36.131Z - info: GET [ecosystem]/plugins.yml
2015-08-30T17:28:46.232Z - error: Error: socket hang up
    at createHangUpError (http.js:1477:15)
    at CleartextStream.socketCloseListener (http.js:1527:23)
    at CleartextStream.emit (events.js:117:20)
    at tls.js:694:10
    at process._tickCallback (node.js:442:13)
```

Looks that everything else works fine. Is it possible that some broken plugin causes this issue? if so, there should be some validator for this kind of case..

**Comment by knownasilya** [comment]
The plugin UI does a request to github, can your server access github?

**Comment by jupe** [comment]
but even it request access, it shouldn't crash like now. Perhaps it just should give response like "please grant server access to github" or something similar.

**Comment by knownasilya** [comment]
Good point
