### ISSUE TITLE
CastError: Cast to ObjectId failed for value

### ISSUE THREAD

**Issue by carlitux** [Strider-CD/strider#862]
Cast to ObjectId failed for value "
> spawn-sync@1.0.13 postinstall /home/repositories/data/carlitux-djarana-561739d96a0cc39a6a2c09ca/node_modules/pre-commit/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

" at path "_id" CastError: Cast to ObjectId failed for value "
> spawn-sync@1.0.13 postinstall /home/repositories/data/carlitux-djarana-561739d96a0cc39a6a2c09ca/node_modules/pre-commit/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

" at path "_id"
    at ObjectId.cast (/home/strider/node_modules/mongoose/lib/schema/objectid.js:117:13)
    at ObjectId.castForQuery (/home/strider/node_modules/mongoose/lib/schema/objectid.js:167:17)
    at Query.cast (/home/strider/node_modules/mongoose/lib/query.js:2361:32)
    at Query.findOne (/home/strider/node_modules/mongoose/lib/query.js:1125:10)
    at Query.exec (/home/strider/node_modules/mongoose/node_modules/mquery/lib/mquery.js:2315:16)
    at Query.exec (/home/strider/node_modules/mongoose/lib/query.js:1813:19)
    at Object.UserSocket.events.build:job (/home/strider/lib/websockets.js:233:31)
    at Socket.emit (events.js:98:17)
    at Socket.onevent (/home/strider/node_modules/socket.io/lib/socket.js:330:8)
    at Socket.onpacket (/home/strider/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/home/strider/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/strider/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/home/strider/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/home/strider/node_modules/socket.io/lib/client.js:175:18)
    at Socket.emit (events.js:95:17)
    at Socket.onPacket (/home/strider/node_modules/socket.io/node_modules/engine.io/lib/socket.js:99:14)
    at XHR.emit (events.js:95:17)
    at XHR.Transport.onPacket (/home/strider/node_modules/socket.io/node_modules/engine.io/lib/transport.js:91:8)
    at callback (/home/strider/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:202:10)
    at Object.exports.decodePayload (/home/strider/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:320:19)
    at XHR.Polling.onData (/home/strider/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:205:10)
    at IncomingMessage.onEnd (/home/strider/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:158:10)
2015-10-09T03:56:57.815Z - error: Error retrieving job
> pre-commit@1.1.1 install /home/repositories/data/carlitux-djarana-561739d96a0cc39a6a2c09ca/node_modules/pre-commit
> node install.js

**Comment by oliversalzburg** [comment]
Seems like this is a problem with `pre-commit` or the way it's used in your project. Can you provide any more details about the project and how/where this happens?

**Comment by carlitux** [comment]
pre-commit is just hit when we did *git commit* command here you can see happens all the time,

2015-10-09T04:01:06.220Z - error: Error retrieving job
 Cast to ObjectId failed for value "
" at path "_id" CastError: Cast to ObjectId failed for value "
" at path "_id"
    at ObjectId.cast (/home/strider/node_modules/mongoose/lib/schema/objectid.js:117:13)
    at ObjectId.castForQuery (/home/strider/node_modules/mongoose/lib/schema/objectid.js:167:17)
    at Query.cast (/home/strider/node_modules/mongoose/lib/query.js:2361:32)
    at Query.findOne (/home/strider/node_modules/mongoose/lib/query.js:1125:10)
    at Query.exec (/home/strider/node_modules/mongoose/node_modules/mquery/lib/mquery.js:2315:16)
    at Query.exec (/home/strider/node_modules/mongoose/lib/query.js:1813:19)
    at Object.UserSocket.events.build:job (/home/strider/lib/websockets.js:233:31)
    at Socket.emit (events.js:98:17)
    at Socket.onevent (/home/strider/node_modules/socket.io/lib/socket.js:330:8)
    at Socket.onpacket (/home/strider/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/home/strider/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/strider/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/home/strider/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/home/strider/node_modules/socket.io/lib/client.js:175:18)
    at Socket.emit (events.js:95:17)
    at Socket.onPacket (/home/strider/node_modules/socket.io/node_modules/engine.io/lib/socket.js:99:14)
    at XHR.emit (events.js:95:17)
    at XHR.Transport.onPacket (/home/strider/node_modules/socket.io/node_modules/engine.io/lib/transport.js:91:8)
    at callback (/home/strider/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:202:10)
    at Object.exports.decodePayload (/home/strider/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:320:19)
    at XHR.Polling.onData (/home/strider/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:205:10)
    at IncomingMessage.onEnd (/home/strider/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:158:10)
2015-10-09T04:01:06.223Z - error: Error retrieving job     activate : node/4.0.0

 Cast to ObjectId failed for value "    activate : node/4.0.0

" at path "_id" CastError: Cast to ObjectId failed for value "    activate : node/4.0.0

" at path "_id"
    at ObjectId.cast (/home/strider/node_modules/mongoose/lib/schema/objectid.js:117:13)
    at ObjectId.castForQuery (/home/strider/node_modules/mongoose/lib/schema/objectid.js:167:17)
    at Query.cast (/home/strider/node_modules/mongoose/lib/query.js:2361:32)
    at Query.findOne (/home/strider/node_modules/mongoose/lib/query.js:1125:10)
    at Query.exec (/home/strider/node_modules/mongoose/node_modules/mquery/lib/mquery.js:2315:16)
    at Query.exec (/home/strider/node_modules/mongoose/lib/query.js:1813:19)
    at Object.UserSocket.events.build:job (/home/strider/lib/websockets.js:233:31)
    at Socket.emit (events.js:98:17)
    at Socket.onevent (/home/strider/node_modules/socket.io/lib/socket.js:330:8)
    at Socket.onpacket (/home/strider/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/home/strider/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/strider/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/home/strider/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/home/strider/node_modules/socket.io/lib/client.js:175:18)
    at Socket.emit (events.js:95:17)
    at Socket.onPacket (/home/strider/node_modules/socket.io/node_modules/engine.io/lib/socket.js:99:14)
    at XHR.emit (events.js:95:17)
    at XHR.Transport.onPacket (/home/strider/node_modules/socket.io/node_modules/engine.io/lib/transport.js:91:8)
    at callback (/home/strider/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:202:10)
    at Object.exports.decodePayload (/home/strider/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:320:19)
    at XHR.Polling.onData (/home/strider/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:205:10)
    at IncomingMessage.onEnd (/home/strider/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:158:10)

looks like ids are not valid and can't retrieve the the job. A lot of errors but on frontend looks like they work but are slow.

**Comment by knownasilya** [comment]
Are you using Node 4.x?

**Comment by carlitux** [comment]
With the project yes, but with strider is 0.10.38 I think.
