### ISSUE TITLE
Unable to start strider on nodejs v4.x 

### ISSUE THREAD

**Issue by isra-shabir** [Strider-CD/strider#899]
I am trying to run Strider after installing nodejs v4.2.4 and npm 2.14.12. 
The steps I follow are:

1) install nodejs and npm:
        curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
        sudo apt-get install -y nodejs

2) $ which nodejs and $which npm give me : /usr/bin/nodejs and /usr/bin/npm
3) clone the strider repository in the home directory
4) ~/strider$ npm install
5) ~/strider$ npm start

Step 5) gives me the following error log:
ubuntu@ip-172-31-45-129:~/strider$ npm start

> strider@1.7.5 start /home/ubuntu/strider
> bin/strider

{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
7495 forked
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
2016-01-05T19:19:10.728Z - info: stubbing smtp..
2016-01-05T19:19:11.030Z - info: Using MongoDB URL: mongodb://localhost/strider-foss
2016-01-05T19:19:11.048Z - warn: No SMTP creds - forgot password flow will not work
2016-01-05T19:19:11.361Z - info: RUNNER INIT
2016-01-05T19:19:11.452Z - info: loaded templates
2016-01-05T19:19:11.553Z - info: initalized webapps
2016-01-05T19:19:11.553Z - info: [job plugins]
2016-01-05T19:19:11.553Z - info: - custom
2016-01-05T19:19:11.553Z - info: - emailnotifier
2016-01-05T19:19:11.553Z - info: - env
2016-01-05T19:19:11.554Z - info: - heroku
2016-01-05T19:19:11.554Z - info: - metadata
2016-01-05T19:19:11.554Z - info: - node
2016-01-05T19:19:11.554Z - info: - python
2016-01-05T19:19:11.554Z - info: - ruby
2016-01-05T19:19:11.554Z - info: - slack
2016-01-05T19:19:11.554Z - info: - ssh_deploy
2016-01-05T19:19:11.554Z - info: [runner plugins]
2016-01-05T19:19:11.554Z - info: - simple-runner
2016-01-05T19:19:11.554Z - info: [provider plugins]
2016-01-05T19:19:11.554Z - info: - bitbucket
2016-01-05T19:19:11.554Z - info: - git
2016-01-05T19:19:11.554Z - info: - github
2016-01-05T19:19:11.554Z - info: - gitlab
2016-01-05T19:19:11.554Z - info: [basic plugins]
2016-01-05T19:19:11.554Z - info: - buildbadge
2016-01-05T19:19:11.556Z - info: initalized static directories
/home/ubuntu/strider/node_modules/less/lib/less/parser/parser.js:117
            imports.contents[fileInfo.filename] = str;
                   ^

TypeError: Cannot read property 'contents' of undefined
    at Object.Parser.parse (/home/ubuntu/strider/node_modules/less/lib/less/parser/parser.js:117:20)
    at /home/ubuntu/strider/node_modules/strider-extension-loader/lib/utils.js:59:12
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
7495 died 1 null
7513 forked

The error just keeps going until I Ctrl-C out of it.

**Comment by knownasilya** [comment]
I just pushed up a new version of strider-extension-loader, so remove your node modules and reinstall. It should fix this issue.

**Comment by isra-shabir** [comment]
@knownasilya - I re-installed nodejs, re-cloned the repo, and now get this output (assuming this does start the service) upon issuing ~/strider$ STRIDER_NODE_ENV=production npm start:

> strider@1.7.5 start /home/ubuntu/strider
> bin/strider

{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
2645 forked
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
2016-01-05T21:03:00.337Z - info: Using SMTP transport from config
2016-01-05T21:03:00.661Z - info: Using MongoDB URL: mongodb://testStrider:1234@localhost:27017/strider
2016-01-05T21:03:01.158Z - info: RUNNER INIT
2016-01-05T21:03:01.291Z - info: loaded templates
2016-01-05T21:03:01.371Z - info: initalized webapps
2016-01-05T21:03:01.371Z - info: [job plugins]
2016-01-05T21:03:01.371Z - info: - custom
2016-01-05T21:03:01.372Z - info: - emailnotifier
2016-01-05T21:03:01.372Z - info: - env
2016-01-05T21:03:01.372Z - info: - heroku
2016-01-05T21:03:01.372Z - info: - metadata
2016-01-05T21:03:01.372Z - info: - node
2016-01-05T21:03:01.372Z - info: - python
2016-01-05T21:03:01.372Z - info: - ruby
2016-01-05T21:03:01.372Z - info: - slack
2016-01-05T21:03:01.372Z - info: - ssh_deploy
2016-01-05T21:03:01.372Z - info: [runner plugins]
2016-01-05T21:03:01.372Z - info: - simple-runner
2016-01-05T21:03:01.372Z - info: [provider plugins]
2016-01-05T21:03:01.372Z - info: - bitbucket
2016-01-05T21:03:01.372Z - info: - git
2016-01-05T21:03:01.372Z - info: - github
2016-01-05T21:03:01.373Z - info: - gitlab
2016-01-05T21:03:01.373Z - info: [basic plugins]
2016-01-05T21:03:01.373Z - info: - buildbadge
2016-01-05T21:03:01.374Z - info: initalized static directories
2016-01-05T21:03:01.399Z - info: loaded config pages
2016-01-05T21:03:01.402Z - info: loaded account config pages
2016-01-05T21:03:01.412Z - info: loaded plugin status blocks
2016-01-05T21:03:01.413Z - info: loaded plugins
2016-01-05T21:03:01.417Z - info: Express server listening on port 4000 in development mode
2016-01-05T21:03:01.417Z - info: Marking zombie jobs as finished...
2016-01-05T21:03:01.422Z - info: 0 zombie jobs marked as finished

It seems like the service now starts (despite the bson module missing error)
I had two persisting questions, however. 
1) Why does it say listening in development mode if I have set STRIDER_NODE_ENV=production?
2) I try to resolve http://<my vm ip:4000/" to access the webapp dashboard, but it never resolves? Does this mean the service may not have started correctly?

**Comment by knownasilya** [comment]
The bson error isn't actually an error that affects strider

1) it should be `NODE_ENV=production`
2) Not sure, since I don't know how you expose your strider instance. nginx?

**Comment by isra-shabir** [comment]
@knownasilya - thank you, the fix starts the service for my machine. I am closing the issue.
