### ISSUE TITLE
Cannot read property 'webhookURL' of undefined at slackPOST

### ISSUE THREAD

**Issue by lucasfeliciano** [Strider-CD/strider#900]
In the cleanup phase this error is not beeing handled.
Should we show a user friendly error message?

```
# TypeError: Cannot read property 'webhookURL' of undefined at slackPOST (/home/strider/strider/node_modules/strider-slack/worker.js:48:29) at EventEmitter.onPhaseDone (/home/strider/strider/node_modules/strider-slack/worker.js:20:13) at EventEmitter.emit (/home/strider/strider/node_modules/eventemitter2/lib/eventemitter2.js:339:22) at Object.Job.status (/home/strider/strider/node_modules/strider-runner-core/lib/job.js:359:18) at Object.Job.phaseDone (/home/strider/strider/node_modules/strider-runner-core/lib/job.js:331:10) at /home/strider/strider/node_modules/strider-runner-core/node_modules/async/lib/async.js:232:13 at /home/strider/strider/node_modules/strider-runner-core/node_modules/async/lib/async.js:142:25 at /home/strider/strider/node_modules/strider-runner-core/node_modules/async/lib/async.js:229:17 at /home/strider/strider/node_modules/strider-runner-core/node_modules/async/lib/async.js:556:34 at Object.runPlugin (/home/strider/strider/node_modules/strider-runner-core/lib/utils.js:24:30) at /home/strider/strider/node_modules/strider-runner-core/lib/job.js:293:15 at /home/strider/strider/node_modules/strider-runner-core/node_modules/async/lib/async.js:551:21 at /home/strider/strider/node_modules/strider-runner-core/node_modules/async/lib/async.js:227:13 at iterate (/home/strider/strider/node_modules/strider-runner-core/node_modules/async/lib/async.js:134:13) at /home/strider/strider/node_modules/strider-runner-core/node_modules/async/lib/async.js:145:25 at /home/strider/strider/node_modules/strider-runner-core/node_modules/async/lib/async.js:229:17 at /home/strider/strider/node_modules/strider-runner-core/node_modules/async/lib/async.js:556:34 at Object.runPlugin (/home/strider/strider/node_modules/strider-runner-core/lib/utils.js:24:30) at /home/strider/strider/node_modules/strider-runner-core/lib/job.js:293:15 at /home/strider/strider/node_modules/strider-runner-core/node_modules/async/lib/async.js:551:21 at /home/strider/strider/node_modules/strider-runner-core/node_modules/async/lib/async.js:227:13 at iterate (/home/strider/strider/node_modules/strider-runner-core/node_modules/async/lib/async.js:134:13)
```

**Comment by knownasilya** [comment]
That looks like an issue with strider-slack, not so much something that needs to be shown, but it should be fixed. Could you open it there?

**Comment by lucasfeliciano** [comment]
Sure, I'm finding a couple of issues with strider-slack.

I'm gathering some information to open the issues there.
But I see that that repository is abandoned, there are open issues from 2014 and a PR from 2015.

Do you know if there is any one maintaining it?

**Comment by knownasilya** [comment]
All repos are as active as there is interest :+1: Feel free to submit PRs or issues. Thanks for the heads up on the PR, will have a look.

**Comment by lucasfeliciano** [comment]
Alright :)

Closing this issue since I'll open it in the right repo!

**Comment by knownasilya** [comment]
FYI, I just merged that old PR and released a new version of the slack plugin, make sure to update in your Plugins section.
