### ISSUE TITLE
Errro Github Auth

### ISSUE THREAD

**Issue by sajov** [Strider-CD/strider#918]
if i try to connect github i got
i was not logged in while trying to connect
Connect
500 Error: You need to enter your email address into Github.
   at makeAccount (/Users/me/Documents/Dev/research/strider/node_modules/strider-github/lib/webapp.js:170:11)
   at Strategy.validateAuth [as _verify] (/Users/me/Documents/Dev/research/strider/node_modules/strider-github/lib/webapp.js:162:26)
   at /Users/me/Documents/Dev/research/strider/node_modules/passport-oauth2/lib/strategy.js:183:24
   at /Users/me/Documents/Dev/research/strider/node_modules/passport-github/lib/strategy.js:174:7
   at passBackControl (/Users/me/Documents/Dev/research/strider/node_modules/oauth/lib/oauth2.js:125:9)
   at IncomingMessage.<anonymous> (/Users/me/Documents/Dev/research/strider/node_modules/oauth/lib/oauth2.js:143:7)
   at emitNone (events.js:72:20)
   at IncomingMessage.emit (events.js:166:7)
   at endReadableNT (_stream_readable.js:905:12)
   at doNTCallback2 (node.js:452:9)
   at process._tickDomainCallback (node.js:407:17) #

**Comment by knownasilya** [comment]
https://github.com/Strider-CD/strider-github#known-issues-with-githubcom
