### ISSUE TITLE
 Git pull failed with code 127

### ISSUE THREAD

**Issue by leomongeg** [Strider-CD/strider#947]
An unexpected error occurred while executing this job. Please report at https://github.com/Strider-CD/strider/issues

```
Git pull failed with code 127

Error: Git pull failed with code 127
    at badCode (/usr/lib/node_modules/strider/node_modules/strider-bitbucket/node_modules/strider-git/worker.js:90:11)
    at updateCache (/usr/lib/node_modules/strider/node_modules/strider-bitbucket/node_modules/strider-git/worker.js:154:19)
    at Object.<anonymous> (/usr/lib/node_modules/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/job.js:195:18)
    at Object.module.exports [as spawn] (/usr/lib/node_modules/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/spawn-normal.js:8:5)
    at Object.Job.cmd (/usr/lib/node_modules/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/job.js:192:17)
    at Object.context.cmd (/usr/lib/node_modules/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/job.js:305:21)
    at /usr/lib/node_modules/strider/node_modules/strider-bitbucket/node_modules/strider-git/worker.js:38:13
    at /usr/lib/node_modules/strider/node_modules/strider-bitbucket/node_modules/strider-git/lib/index.js:125:5
    at Function.<anonymous> (/usr/lib/node_modules/strider/node_modules/strider-bitbucket/node_modules/strider-git/node_modules/gitane/index.js:173:7)
    at next (/usr/lib/node_modules/strider/node_modules/strider-bitbucket/node_modules/step/lib/step.js:51:23)
    at next (/usr/lib/node_modules/strider/node_modules/strider-bitbucket/node_modules/step/lib/step.js:54:7)
    at Function.<anonymous> (/usr/lib/node_modules/strider/node_modules/strider-bitbucket/node_modules/strider-git/node_modules/gitane/index.js:76:14)
    at next (/usr/lib/node_modules/strider/node_modules/strider-bitbucket/node_modules/step/lib/step.js:51:23)
    at /usr/lib/node_modules/strider/node_modules/strider-bitbucket/node_modules/step/lib/step.js:83:14
    at Object.oncomplete (fs.js:108:15)
```

**Comment by knownasilya** [comment]
This is related to your other issue, 127 means it doesn't understand your command. Looks like you don't have git installed, have an old version of git, or you have a bad install of git..
