### ISSUE TITLE
Failed to start command: ["git",["--version"]]

### ISSUE THREAD

**Issue by leomongeg** [Strider-CD/strider#948]
An unexpected error occurred while executing this job. Please report at https://github.com/Strider-CD/strider/issues

Failed to start command: ["git",["--version"]]

Error: Failed to start command: ["git",["--version"]]
    at safespawn (/usr/lib/node_modules/strider/node_modules/strider-bitbucket/node_modules/strider-git/worker.js:13:11)
    at gitVersion (/usr/lib/node_modules/strider/node_modules/strider-bitbucket/node_modules/strider-git/worker.js:46:15)
    at clone (/usr/lib/node_modules/strider/node_modules/strider-bitbucket/node_modules/strider-git/worker.js:66:3)
    at /usr/lib/node_modules/strider/node_modules/strider-bitbucket/node_modules/strider-git/worker.js:133:7
    at /usr/lib/node_modules/strider/node_modules/strider-bitbucket/node_modules/strider-git/node_modules/fs-extra/node_modules/mkdirp/index.js:38:26
    at Object.oncomplete (fs.js:108:15)

**Comment by leomongeg** [comment]
Hi folks,
the error persists until run a "strider restart", after restart the strider all works fine, but the error is triggered random.

**Comment by knownasilya** [comment]
Do you have `git` 2.0 or greater installed?

**Comment by leomongeg** [comment]
Hi, 

Yes my mistake, the server is installed with git version 1.9.1. I'm going to update to version 2.0

Thanks

**Comment by knownasilya** [comment]
Did updating help?
