### ISSUE TITLE
README addition - mention krb5-devel possibly needing installation before npm install

### ISSUE THREAD

**Issue by arimus** [Strider-CD/strider#955]
Just as a note for others that may run into this issue on CentOS: you may want to note that it may be necessary to "yum install krb5-devel" on CentOS 7.1 and likely other versions / distros for strider to successfully build without error. 

**Versions**

[root@test test]# node --version
v4.4.7
[root@test test]# npm --version
2.15.8

**Log Messages**
```shell
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN peerDependencies The peer dependency kerberos@~0.0 included from mongodb-core will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

> kerberos@0.0.11 install /usr/lib/node_modules/strider/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/lib/node_modules/strider/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
make: Leaving directory `/usr/lib/node_modules/strider/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/build'

> bson@0.2.22 install /usr/lib/node_modules/strider/node_modules/mongoose/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/lib/node_modules/strider/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
make: Leaving directory `/usr/lib/node_modules/strider/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'

> kerberos@0.0.21 install /usr/lib/node_modules/strider/node_modules/connect-mongo/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.4.7"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/strider/node_modules/connect-mongo/node_modules/mongodb/node_modules/kerberos/.node-gyp"
make: Entering directory `/usr/lib/node_modules/strider/node_modules/connect-mongo/node_modules/mongodb/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory `/usr/lib/node_modules/strider/node_modules/connect-mongo/node_modules/mongodb/node_modules/kerberos/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-229.7.2.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/strider/node_modules/connect-mongo/node_modules/mongodb/node_modules/kerberos
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
```

**Comment by chusri** [comment]
@arimus did you solved this problem ?

**Comment by arimus** [comment]
Yes, the problem was solved by installing the krb5-devel package as mentioned above. I opened this ticket so that the docs could be updated to mention this fact.

**Comment by oliversalzburg** [comment]
Added a note to the README
