### ISSUE TITLE
Object #<Object> has no method 'log'

### ISSUE THREAD

**Issue by theNailz** [Strider-CD/strider#963]
After moving from my development VM to a hosted VM, I can't get my strider running again. I'm greeted with the following error, 1 minute after hitting the Test button:

![strider_error](https://cloud.githubusercontent.com/assets/983043/17093410/7694d8de-5249-11e6-9118-9a88665c40d5.png)

I do see the .git repo complete in .strider/<project>-hash/ and it looks fine.
There is 1 plugin active, "custom scripts" which has no content in any of the steps.

strider@1.7.7

**Comment by oliversalzburg** [comment]
Can you check the plugins section and see what version of strider-git is installed? Line 118 is an empty line in the latest version.

**Comment by theNailz** [comment]
├─┬ strider-git@0.2.5
├─┬ strider-github@2.3.1
├─┬ strider-gitlab@1.2.5
 │ ├── strider-git@0.1.1

**Comment by oliversalzburg** [comment]
The `context.log` ability was removed from strider. You should update all installed plugins to the latest version.

@knownasilya Could we make another release of `strider-git`, bump the dependency in strider and strider-gitlab/bitbucket/github as needed and push new releases for those as well?

**Comment by theNailz** [comment]
Running `npm update` in the strider directory did fix this problem. Now I'm facing a new problem, which I believe might be a Git problem?
```
Error: Checkout failed with code 127
    at badCode (/home/itbo/strider/node_modules/strider/node_modules/strider-git/worker.js:93:11)
    at /home/itbo/strider/node_modules/strider/node_modules/strider-git/worker.js:124:22
    at Object.<anonymous> (/home/itbo/strider/node_modules/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/job.js:200:18)
    at Object.module.exports [as spawn] (/home/itbo/strider/node_modules/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/spawn-normal.js:9:5)
    at Object.Job.cmd (/home/itbo/strider/node_modules/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/job.js:197:17)
    at context.cmd (/home/itbo/strider/node_modules/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/job.js:304:21)
    at checkoutRef (/home/itbo/strider/node_modules/strider/node_modules/strider-git/worker.js:120:10)
    at gotten (/home/itbo/strider/node_modules/strider/node_modules/strider-git/worker.js:174:14)
    at updateCache (/home/itbo/strider/node_modules/strider/node_modules/strider-git/worker.js:162:14)
    at /home/itbo/strider/node_modules/strider/node_modules/strider-git/lib/index.js:126:5
    at Function.<anonymous> (/home/itbo/strider/node_modules/strider/node_modules/strider-git/node_modules/gitane/index.js:173:7)
    at next (/home/itbo/strider/node_modules/strider/node_modules/step/lib/step.js:51:23)
    at ChildProcess.<anonymous> (/home/itbo/strider/node_modules/strider/node_modules/strider-git/node_modules/gitane/index.js:159:9)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```

**Comment by oliversalzburg** [comment]
What happens if you manually attempt to `git checkout` (as the strider user) in the cloned repo?

**Comment by theNailz** [comment]
Does strider exec this in the .strider/data/<repo> folder?

**Comment by oliversalzburg** [comment]
Yeah, there should be a clone of your git repo there.

**Comment by xgalen** [comment]
Closing this because the issue was solved as the creator said.
