### ISSUE TITLE
error: undefined

### ISSUE THREAD

**Issue by crobinson42** [Strider-CD/strider#968]
I saw a not so descriptive error in my logs... 

```
strider-0 (err): 2016-07-27T23:39:28.210Z - error: undefined
strider-0 (err): 2016-07-27T23:39:28.223Z - error: TypeError: Cannot set property 'errored' of undefined
strider-0 (err):     at /home/admin/.nvm/versions/node/v4.4.7/lib/node_modules/strider/node_modules/strider-simple-runner/lib/index.js:375:29
strider-0 (err):     at Object.Job.done (/home/admin/.nvm/versions/node/v4.4.7/lib/node_modules/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/job.js:145:5)
strider-0 (err):     at Domain.<anonymous> (/home/admin/.nvm/versions/node/v4.4.7/lib/node_modules/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/job.js:94:12)
strider-0 (err):     at emitOne (events.js:77:13)
strider-0 (err):     at Domain.emit (events.js:169:7)
strider-0 (err):     at SMTPClient.emit (events.js:139:14)
strider-0 (err):     at SMTPClient._onError (/home/admin/.nvm/versions/node/v4.4.7/lib/node_modules/strider/node_modules/strider-mailer/node_modules/nodemailer/node_modules/simplesmtp/lib/client.js:373:10)
strider-0 (err):     at emitOne (events.js:82:20)
strider-0 (err):     at TLSSocket.emit (events.js:169:7)
strider-0 (err):     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._emitTLSError (_tls_wrap.js:545:10)
strider-0 (err):     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onocspresponse.ssl.onerror (_tls_wrap.js:445:12)
strider-0 (err): js-bson: Failed to load c++ bson extension, using pure JS version
strider-0 (err): 2016-07-28T00:20:18.032Z - error: undefined
```

**Comment by crobinson42** [comment]
This happened after I cancelled a job. Will provide more info if it happens again.

**Comment by crobinson42** [comment]
Ok, I've figured it out. I'm using SSH Deploy plugin and I cancel the job with I see the console message "Authentication methods have failed". This is what causes the failure and breaks Strider.

```
strider-0 (out): 2016-07-28T01:10:52.639Z - info: Got a request to cancel 579959ac6054dcc567ab060d

strider-0 (err): 2016-07-27T23:39:28.223Z - error: TypeError: Cannot set property 'errored' of undefined
strider-0 (err):     at /home/admin/.nvm/versions/node/v4.4.7/lib/node_modules/strider/node_modules/strider-simple-runner/lib/index.js:375:29
strider-0 (err):     at Object.Job.done (/home/admin/.nvm/versions/node/v4.4.7/lib/node_modules/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/job.js:145:5)
strider-0 (err):     at Domain.<anonymous> (/home/admin/.nvm/versions/node/v4.4.7/lib/node_modules/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/job.js:94:12)
strider-0 (err):     at emitOne (events.js:77:13)
strider-0 (err):     at Domain.emit (events.js:169:7)
strider-0 (err):     at SMTPClient.emit (events.js:139:14)
strider-0 (err):     at SMTPClient._onError (/home/admin/.nvm/versions/node/v4.4.7/lib/node_modules/strider/node_modules/strider-mailer/node_modules/nodemailer/node_modules/simplesmtp/lib/client.js:373:10)
strider-0 (err):     at emitOne (events.js:82:20)
strider-0 (err):     at TLSSocket.emit (events.js:169:7)
strider-0 (err):     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._emitTLSError (_tls_wrap.js:545:10)
strider-0 (err):     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onocspresponse.ssl.onerror (_tls_wrap.js:445:12)
strider-0 (err): js-bson: Failed to load c++ bson extension, using pure JS version
strider-0 (err): 2016-07-28T00:20:18.032Z - error: undefined
strider-0 (err): js-bson: Failed to load c++ bson extension, using pure JS version
strider-0 (err): js-bson: Failed to load c++ bson extension, using pure JS version
strider-0 (err): 2016-07-28T01:00:40.357Z - error: undefined
strider-0 (err): js-bson: Failed to load c++ bson extension, using pure JS version
strider-0 (err): js-bson: Failed to load c++ bson extension, using pure JS version
strider-0 (err): 2016-07-28T01:10:55.197Z - error: undefined
```

**Comment by knownasilya** [comment]
This should be fixed as of this morning in the simple runner, I just need to release.

**Comment by knownasilya** [comment]
I've published simple-runner as 1.0 and updated this repo with the new version. You can also use the plugin manager in the ui to update. Make sure you run Strider with Node 4.2 or greater.

**Comment by crobinson42** [comment]
thx!

**Comment by crobinson42** [comment]
@knownasilya I upgrade simple-runner but now strider won't run:

```
admin@jenkins:~$ strider
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
21221 forked
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
21221 died 1 null
21235 forked
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
21235 died 1 null
21245 forked
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
^C
```

I'm using node v4.4.7 on a linux box.

**Comment by crobinson42** [comment]
I tried `npm update -g strider` which updated to `v1.8.0`, same result. Uninstalled w/ `npm uninstall -g strider` then reinstalled (`v1.8.0`), same result. Then I tried uninstalling and reinstalling `v1.7.7` which is the last version working on my box, and I'm seeing a slightly different error:

```
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
23896 forked
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
2016-07-29T21:01:00.913Z - info: Using MongoDB URL: mongodb://localhost/strider-foss
2016-07-29T21:01:01.066Z - error: Could not connect to DB: Error: failed to connect to [localhost:27017]
23896 died 1 null
23909 forked
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
2016-07-29T21:01:03.822Z - info: Using MongoDB URL: mongodb://localhost/strider-foss
2016-07-29T21:01:03.939Z - error: Could not connect to DB: Error: failed to connect to [localhost:27017]
23909 died 1 null
23918 forked
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
^C
```

**Comment by crobinson42** [comment]
Haha..don't ask how, but my mongo db dir was deleted somewhere in the process of upgrading the `simple-runner` 👎  It must be Friday.
