### ISSUE TITLE
Strider “npm start” generating errors

### ISSUE THREAD

**Issue by mark-norgate** [Strider-CD/strider#970]
I am trying to install a Strider instance on an AWS EC2 instance. I have installed all the perquisites as described in [this document](https://futurestud.io/blog/strider-how-to-install-the-platform-and-plugins) but have run across a problem running Strider using npm start.

I have confirmed that MongoDB is running correctly.

I will eventually run it as a service, but I'd like to check it's running first. I receive pages of errors along the lines of:

> strider@1.8.0 start /home/ubuntu/strider
> bin/strider

```
7577 forked
module.js:341
    throw err;
    ^

Error: Cannot find module '../../../models'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/ubuntu/strider/lib/routes/collaborators/api.js:3:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/ubuntu/strider/lib/routes/collaborators/index.js:9:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/ubuntu/strider/lib/app.js:44:27)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/ubuntu/strider/main.js:9:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
7577 died 1 null

```
I have looked at [this overflow](http://stackoverflow.com/questions/14226410/node-js-cannot-find-module-mongodb) but it doesn't solve my problem unfortunately. I do not appear to have a `server.js` anywhere.

Do I need one of these? Am I configuring it correctly? Incidentally, my Strider instance is located in
`/home/ubuntu` but not really being a Unix bunny, I'm not sure if this is really where it ought to go.

Any help greatly appreciated.

**Comment by knownasilya** [comment]
You must have pull down master, try installing the stable version via `npm install -g strider` or checkout the `v1.8.0` tag if you clone it yourself. If you still want to do canary, then just pull down the latest code, it should be fixed.
