### ISSUE TITLE
Strider crush after loading localhost:3000

### ISSUE THREAD

**Issue by nenadb97** [Strider-CD/strider#993]
> strider@1.9.3 start /home/devops/strider
> bin/strider

11605 forked
2016-09-14T12:33:45.756Z - warn: Unhandled rejection TypeError: Cannot read property 'plugins' of null
    at sanitizeBranch (/home/devops/strider/lib/utils/index.js:179:29)
    at Array.map (native)
    at Object.sanitizeProject (/home/devops/strider/lib/utils/index.js:205:32)
    at jobProject (/home/devops/strider/lib/jobs.js:63:19)
    at /home/devops/strider/lib/jobs.js:84:19
    at /home/devops/strider/node_modules/mongoose/lib/query.js:2257:18
    at tryCatcher (/home/devops/strider/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/devops/strider/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/devops/strider/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/devops/strider/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/devops/strider/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/devops/strider/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/devops/strider/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/home/devops/strider/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

**Comment by knownasilya** [comment]
Probably related to #992

**Comment by knownasilya** [comment]
Try version 1.9.4

**Comment by nenadb97** [comment]
I tried a couple of versions but result is same.
The latest version worked well yesterday, but when I added branch to my project this error occurred.
Also I reinstalled and change version of NodeJS but nothing. Does Strider save some cache or configuration out of his folder, maby solution is hidden there?

**Comment by nenadb97** [comment]
That release work fine. Thank you.

**Comment by knownasilya** [comment]
Excellent

**Comment by nenadb97** [comment]
LOL. It worked unitl Strider was restarted. After restart error occurred again...

**Comment by knownasilya** [comment]
I'd delete and re-add your project.

**Comment by nenadb97** [comment]
Yes, but it's not possible. Because this error don't allow me to access the Web interface. It give me 404, server is not running.

**Comment by knownasilya** [comment]
you can delete your database
